/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsGestor;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Administrador
 */
public class PanelRevisarSol extends javax.swing.JPanel {

    /**
     * Creates new form PanelRevisarSol
     */
    public PanelRevisarSol() {
        initComponents();
    }

    public void mostrarTipo(JPanel j) {

        j.setSize(880, 370);
        j.setLocation(0, 0);

        PnlReaction.removeAll();
        PnlReaction.add(j, BorderLayout.CENTER);
        PnlReaction.revalidate();
        PnlReaction.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlBase = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlBotones = new javax.swing.JPanel();
        BtnCambioDoc = new javax.swing.JButton();
        BtnRetiroCurso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PnlReaction = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1160, 537));

        PnlBase.setBackground(new java.awt.Color(57, 91, 126));
        PnlBase.setPreferredSize(new java.awt.Dimension(1160, 540));

        jPanel2.setBackground(new java.awt.Color(16, 122, 149));
        jPanel2.setPreferredSize(new java.awt.Dimension(1160, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(411, 56));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solicitudes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 412, 52));

        PnlBotones.setBackground(new java.awt.Color(0, 102, 204));

        BtnCambioDoc.setBackground(new java.awt.Color(25, 25, 112));
        BtnCambioDoc.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnCambioDoc.setForeground(new java.awt.Color(255, 255, 255));
        BtnCambioDoc.setText("Cambios de Docentes");
        BtnCambioDoc.setBorder(null);
        BtnCambioDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambioDocActionPerformed(evt);
            }
        });

        BtnRetiroCurso.setBackground(new java.awt.Color(25, 25, 112));
        BtnRetiroCurso.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnRetiroCurso.setForeground(new java.awt.Color(255, 255, 255));
        BtnRetiroCurso.setText("Retiros de Curso");
        BtnRetiroCurso.setBorder(null);
        BtnRetiroCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetiroCursoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/solicitudesrevisarpeque.png"))); // NOI18N

        javax.swing.GroupLayout PnlBotonesLayout = new javax.swing.GroupLayout(PnlBotones);
        PnlBotones.setLayout(PnlBotonesLayout);
        PnlBotonesLayout.setHorizontalGroup(
            PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBotonesLayout.createSequentialGroup()
                .addGroup(PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCambioDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRetiroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PnlBotonesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlBotonesLayout.setVerticalGroup(
            PnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBotonesLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCambioDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnRetiroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        PnlReaction.setBackground(new java.awt.Color(57, 91, 126));

        javax.swing.GroupLayout PnlReactionLayout = new javax.swing.GroupLayout(PnlReaction);
        PnlReaction.setLayout(PnlReactionLayout);
        PnlReactionLayout.setHorizontalGroup(
            PnlReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        PnlReactionLayout.setVerticalGroup(
            PnlReactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PnlBaseLayout = new javax.swing.GroupLayout(PnlBase);
        PnlBase.setLayout(PnlBaseLayout);
        PnlBaseLayout.setHorizontalGroup(
            PnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PnlBaseLayout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(PnlReaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(PnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PnlBaseLayout.setVerticalGroup(
            PnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBaseLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(PnlReaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PnlBaseLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(PnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetiroCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetiroCursoActionPerformed
       RevisarRetiroCurso RRC = new RevisarRetiroCurso();
        mostrarTipo(RRC);

    }//GEN-LAST:event_BtnRetiroCursoActionPerformed

    private void BtnCambioDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambioDocActionPerformed
        RevisarCambioDoc RCD = new RevisarCambioDoc();
        mostrarTipo(RCD);
    }//GEN-LAST:event_BtnCambioDocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCambioDoc;
    private javax.swing.JButton BtnRetiroCurso;
    private javax.swing.JPanel PnlBase;
    private javax.swing.JPanel PnlBotones;
    private javax.swing.JPanel PnlReaction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
