/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsGestor;

import DAO.Tablas;
import Informacion.EstadoPeriodos;
import Informacion.ValoresEstaticos;
import Interfaces.Estados;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class PanelConfiguracionPeriodo extends javax.swing.JPanel {

    /**
     * Creates new form PanelConfiguracionPeriodo
     */
    Tablas Tbl = new Tablas();
    Estados E = new Estados();
    int fila;
    EstadoPeriodos VEPST = ValoresEstaticos.VEPST;

    public PanelConfiguracionPeriodo() {
        initComponents();
        TxtAreaExplicacion.setEnabled(false);
        Tbl.CargarTablaPeriodos(TblPeriodos, "periodos", "");
        BtnGuardar.setEnabled(false);
        CmbEstadoSelect.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPeriodos = new javax.swing.JTable();
        LblNombreSelect = new javax.swing.JLabel();
        CmbEstadoSelect = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaExplicacion = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1160, 537));

        jPanel1.setBackground(new java.awt.Color(57, 91, 126));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERIODOS:");

        TblPeriodos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TblPeriodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TblPeriodosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TblPeriodos);

        LblNombreSelect.setBackground(new java.awt.Color(255, 255, 255));
        LblNombreSelect.setForeground(new java.awt.Color(0, 0, 0));
        LblNombreSelect.setText("-");
        LblNombreSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        CmbEstadoSelect.setBackground(new java.awt.Color(255, 255, 255));
        CmbEstadoSelect.setForeground(new java.awt.Color(0, 0, 0));
        CmbEstadoSelect.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        CmbEstadoSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbEstadoSelectActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECCION:");

        BtnGuardar.setBackground(new java.awt.Color(0, 51, 204));
        BtnGuardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/guardar32x32.png"))); // NOI18N
        BtnGuardar.setText("Guardar Cambios");
        BtnGuardar.setBorder(null);
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        TxtAreaExplicacion.setBackground(new java.awt.Color(0, 153, 204));
        TxtAreaExplicacion.setColumns(20);
        TxtAreaExplicacion.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        TxtAreaExplicacion.setForeground(new java.awt.Color(0, 0, 0));
        TxtAreaExplicacion.setRows(5);
        TxtAreaExplicacion.setText("Solo un periodo puede ser \ndiferente de cerrado.\nTodas las acciones que haga\ndentro del sistema, se \naplicaran al periodo el cual \nsu estado sea \ndiferente a Cerrado.");
        TxtAreaExplicacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(TxtAreaExplicacion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(222, 222, 222)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(LblNombreSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(CmbEstadoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)))))
                .addGap(639, 639, 639))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(LblNombreSelect)
                        .addGap(18, 18, 18)
                        .addComponent(CmbEstadoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TblPeriodosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPeriodosMousePressed
        fila = TblPeriodos.getSelectedRow();

        if (fila != -1) {
            CmbEstadoSelect.removeAllItems();
            String Nombre = TblPeriodos.getValueAt(fila, TblPeriodos.getColumnModel().getColumnIndex("Nombre")).toString();
            String estado = TblPeriodos.getValueAt(fila, TblPeriodos.getColumnModel().getColumnIndex("Estado")).toString();

//            String Nombreproximo = TblPeriodos.getValueAt(fila + 1, TblPeriodos.getColumnModel().getColumnIndex("Nombre")).toString();
            //    String estadoproximo = TblPeriodos.getValueAt(fila + 1, TblPeriodos.getColumnModel().getColumnIndex("Estado")).toString();
            if (Nombre.equals(VEPST.getNombrep())) {
                CmbEstadoSelect.setEnabled(true);
                LblNombreSelect.setText(Nombre);
                if (estado.equals("Cerrado")) {
                    CmbEstadoSelect.addItem("Cerrado");
                    CmbEstadoSelect.addItem("Prematricula");
                } else {
                    if (estado.equals("Prematricula")) {
                        CmbEstadoSelect.addItem("Cerrado");
                        CmbEstadoSelect.addItem("Prematricula");
                        CmbEstadoSelect.addItem("Matricula Abierta");
                        CmbEstadoSelect.setSelectedIndex(1);
                    } else {
                        if (estado.equals("Matricula Abierta")) {
                            CmbEstadoSelect.addItem("Matricula Abierta");
                            CmbEstadoSelect.addItem("En Curso");
                        } else {
                            if (estado.equals("En Curso")) {
                                CmbEstadoSelect.addItem("En Curso");
                                CmbEstadoSelect.addItem("Finalizado");
                            }
                        }
                    }
                }

            } else {
                if (estado.equals("Finalizado")) {
                    JOptionPane.showMessageDialog(null, "Ya finalizó este periodo, no puede manipular este periodo");
                } else {
                    if ((estado.equals("Cerrado") || estado.equals("Prematricula")) && E.ValidarMatricula() == 0) {
                        CmbEstadoSelect.setEnabled(true);
                        LblNombreSelect.setText(Nombre);
                        if (estado.equals("Cerrado")) {
                            CmbEstadoSelect.addItem("Cerrado");
                            CmbEstadoSelect.addItem("Prematricula");
                        } else {
                            if (estado.equals("Prematricula")) {

                                CmbEstadoSelect.addItem("Prematricula");
                                CmbEstadoSelect.addItem("Cerrado");
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El periodo actual ya esta en funcionamiento \n no puede realizar cambios en otros periodos hasta que el actual finalice");
                    }
                }

            }

        }
    }//GEN-LAST:event_TblPeriodosMousePressed

    private void CmbEstadoSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbEstadoSelectActionPerformed
        int OpcionesEstado = (int) CmbEstadoSelect.getItemCount();
        String estadoactual;
        if (OpcionesEstado > 2) {
            estadoactual = (String) CmbEstadoSelect.getItemAt(1);
        } else {
            estadoactual = (String) CmbEstadoSelect.getItemAt(0);
        }

        String nuevoestado = (String) CmbEstadoSelect.getSelectedItem();

        if (estadoactual != null) {
            if (estadoactual.equals(nuevoestado)) {
                BtnGuardar.setEnabled(false);
            } else {
                BtnGuardar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_CmbEstadoSelectActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        String nombreactual = LblNombreSelect.getText();
        String estadoactual = (String) CmbEstadoSelect.getSelectedItem();
        E.CambiarPeriodo(nombreactual, estadoactual);
        if (estadoactual.equals("En Curso")) {
            E.SeccionesxNotasTipoParticipacion();
        }
        if (estadoactual.equals("Finalizado")) {
            E.actualizarCiclo();
            E.actualizarBecas();
            E.actualizarPagos();
            E.actualizarSecciones();
}
        
        LblNombreSelect.setText("-");
        CmbEstadoSelect.removeAllItems();
        CmbEstadoSelect.setEnabled(false);
        TblPeriodos.removeAll();
        Tbl.CargarTablaPeriodos(TblPeriodos, "periodos", "");
        E.DefinirPeriodo();
    }//GEN-LAST:event_BtnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> CmbEstadoSelect;
    private javax.swing.JLabel LblNombreSelect;
    private javax.swing.JTable TblPeriodos;
    private javax.swing.JTextArea TxtAreaExplicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
