/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsGestor;

import Informacion.SolDocentes;
import Informacion.ValoresEstaticos;
import Interfaces.DAOSolicitudesImplement;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class ProcCambioDoc extends javax.swing.JPanel {
    
    SolDocentes VESDoc = ValoresEstaticos.SDoc;
    SolDocentes SD = new SolDocentes();
    DAOSolicitudesImplement DAOSI = new DAOSolicitudesImplement();
    int val;

    /**
     * Creates new form RevisarCambioDoc
     */
    public ProcCambioDoc() {
        initComponents();
        LblIDSolicitud.setText(Integer.toString(VESDoc.getIDSol()));
        LblDocente.setText(VESDoc.getCodDocenteAntiguo());
        LblSeccion.setText(Integer.toString(VESDoc.getNroSeccion()));
        
        SD.setIDSol(VESDoc.getIDSol());
        SD.setNroSeccion(VESDoc.getNroSeccion());
        SD.setCodDocenteAntiguo(VESDoc.getCodDocenteAntiguo());
        SD.setEstado(VESDoc.getEstado());
        DAOSI.ObtenerInfoCurso(SD);
        LblNombredelCurso.setText(SD.getNombreCurso());
        DAOSI.getHorarios(SD);
        val = DAOSI.ObtenerDocentesDisponibles(SD, CmbDocente);
        if (val < 1) {
            CmbDocente.setEnabled(false);
        } else {
            LimpiarTabla(TblCurso);
            CargarTabla(TblCurso);
        }
    }
    
    private void CargarTabla(JTable tabla) {
        DefaultTableModel modeloTablacurso = (DefaultTableModel) tabla.getModel();
        
        modeloTablacurso.addRow(new Object[]{
            "Diurno", AsignarX("lunes", "diurno"), AsignarX("martes", "diurno"), AsignarX("miercoles", "diurno"), AsignarX("jueves", "diurno"), AsignarX("viernes", "diurno"), AsignarX("sabado", "diurno")
        });
        
        modeloTablacurso.addRow(new Object[]{
            "Nocturno", AsignarX("lunes", "nocturno"), AsignarX("martes", "nocturno"), AsignarX("miercoles", "nocturno"), AsignarX("jueves", "nocturno"), AsignarX("viernes", "nocturno"), AsignarX("sabado", "nocturno")
        });
        
    }
    
    private void LimpiarTabla(JTable tabla) {
        DefaultTableModel modeloTablacurso = (DefaultTableModel) tabla.getModel();
        int filas = modeloTablacurso.getRowCount();
        for (int i = 0; i < filas; i++) {
            
            modeloTablacurso.removeRow(0);
        }
    }
    
    private String AsignarX(String dia, String turno) {
        String valor = "";
        String turnoreal1, turnoreal2, diareal1, diareal2;
        turnoreal1 = SD.getTurnoEsp(0);
        turnoreal2 = SD.getTurnoEsp(1);
        diareal1 = SD.getDiasemanaEsp(0);
        diareal2 = SD.getDiasemanaEsp(1);
        if (SD.getTurnoEsp(1).equals("nada")) {
            if (turno.equals(turnoreal1)) {
                if (dia.equals(diareal1)) {
                    valor = "X";
                }
            }
        } else {
            if (turno.equals(turnoreal1)) {
                if (dia.equals(diareal1)) {
                    valor = "X";
                }
                
            }
            if (turno.equals(turnoreal2)) {
                if (dia.equals(diareal2)) {
                    valor = "X";
                }
                
            }
        }
        
        return valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlReaction3 = new javax.swing.JPanel();
        LblIDSolicitud = new javax.swing.JLabel();
        LblDocente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnProcesar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCurso = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        CmbDocente = new javax.swing.JComboBox<>();
        LblNombreDocente = new javax.swing.JLabel();
        LblProfesionDocente = new javax.swing.JLabel();
        lblreloj = new javax.swing.JLabel();
        LblNombredelCurso = new javax.swing.JLabel();
        LblSeccion = new javax.swing.JLabel();

        PnlReaction3.setBackground(new java.awt.Color(57, 91, 126));
        PnlReaction3.setMaximumSize(new java.awt.Dimension(900, 388));
        PnlReaction3.setMinimumSize(new java.awt.Dimension(900, 388));
        PnlReaction3.setName(""); // NOI18N

        LblIDSolicitud.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        LblIDSolicitud.setForeground(new java.awt.Color(255, 255, 255));
        LblIDSolicitud.setText("-");
        LblIDSolicitud.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID de Solicitud", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        LblDocente.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        LblDocente.setForeground(new java.awt.Color(255, 255, 255));
        LblDocente.setText("-");
        LblDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docente Antiguo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INFORMACION");

        BtnProcesar.setBackground(new java.awt.Color(153, 0, 26));
        BtnProcesar.setFont(new java.awt.Font("Eras Light ITC", 1, 12)); // NOI18N
        BtnProcesar.setForeground(new java.awt.Color(255, 255, 255));
        BtnProcesar.setText("Cambiar");
        BtnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcesarActionPerformed(evt);
            }
        });

        TblCurso.setAutoCreateRowSorter(true);
        TblCurso.setBackground(new java.awt.Color(0, 0, 0));
        TblCurso.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 0)));
        TblCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TblCurso.setForeground(new java.awt.Color(255, 0, 51));
        TblCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turno", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TblCurso.setGridColor(new java.awt.Color(255, 255, 255));
        TblCurso.setSelectionForeground(new java.awt.Color(242, 242, 209));
        TblCurso.setShowGrid(true);
        jScrollPane1.setViewportView(TblCurso);

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Curso");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel11)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(0, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 105));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Docentes Disponibles:");

        CmbDocente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CmbDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docentes ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12))); // NOI18N
        CmbDocente.setPreferredSize(new java.awt.Dimension(180, 50));
        CmbDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbDocenteActionPerformed(evt);
            }
        });

        LblNombreDocente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNombreDocente.setForeground(new java.awt.Color(255, 255, 255));
        LblNombreDocente.setText("-");
        LblNombreDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docente Nuevo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        LblNombreDocente.setPreferredSize(new java.awt.Dimension(180, 50));

        LblProfesionDocente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblProfesionDocente.setForeground(new java.awt.Color(255, 255, 255));
        LblProfesionDocente.setText("-");
        LblProfesionDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profesión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        LblProfesionDocente.setPreferredSize(new java.awt.Dimension(180, 50));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addComponent(LblNombreDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblProfesionDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(LblNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblProfesionDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        lblreloj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/horar.png"))); // NOI18N

        LblNombredelCurso.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        LblNombredelCurso.setForeground(new java.awt.Color(255, 255, 255));
        LblNombredelCurso.setText("-");
        LblNombredelCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        LblSeccion.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        LblSeccion.setForeground(new java.awt.Color(255, 255, 255));
        LblSeccion.setText("-");
        LblSeccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nro de Seccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        javax.swing.GroupLayout PnlReaction3Layout = new javax.swing.GroupLayout(PnlReaction3);
        PnlReaction3.setLayout(PnlReaction3Layout);
        PnlReaction3Layout.setHorizontalGroup(
            PnlReaction3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlReaction3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PnlReaction3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlReaction3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblIDSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNombredelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PnlReaction3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlReaction3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PnlReaction3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlReaction3Layout.createSequentialGroup()
                                .addComponent(lblreloj, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlReaction3Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(BtnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PnlReaction3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PnlReaction3Layout.setVerticalGroup(
            PnlReaction3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlReaction3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LblIDSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(LblDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(LblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(LblNombredelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PnlReaction3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PnlReaction3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PnlReaction3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblreloj)
                    .addGroup(PnlReaction3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(BtnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlReaction3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlReaction3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CmbDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbDocenteActionPerformed
        
        if (CmbDocente.getItemCount() > 0) {
            SD.setCodDocenteNuevo((String) CmbDocente.getSelectedItem());
            DAOSI.ObtenerInfoDocente(SD);
            LblNombreDocente.setText(SD.getNmcDocenteNuevo());
            LblProfesionDocente.setText(SD.getEspecializacionDocNuevo());
        } else {
            LblNombreDocente.setText("-");
            LblProfesionDocente.setText("-");
        }
    }//GEN-LAST:event_CmbDocenteActionPerformed

    private void BtnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcesarActionPerformed
        DAOSI.ActualizarDocente(SD);
        DAOSI.cambiarEstadoSolicitudDocente(SD);
        JOptionPane.showMessageDialog(null, "Solicitud procesada\nCambio de docente completado");
        RevisarCambioDoc RCD = new RevisarCambioDoc();
        mostrarTipo(RCD);
    }//GEN-LAST:event_BtnProcesarActionPerformed
 public void mostrarTipo(JPanel j) {

        j.setSize(880, 370);
        j.setLocation(0, 0);

        PnlReaction3.removeAll();
        PnlReaction3.add(j, BorderLayout.CENTER);
        PnlReaction3.revalidate();
        PnlReaction3.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnProcesar;
    private javax.swing.JComboBox<String> CmbDocente;
    private javax.swing.JLabel LblDocente;
    private javax.swing.JLabel LblIDSolicitud;
    private javax.swing.JLabel LblNombreDocente;
    private javax.swing.JLabel LblNombredelCurso;
    private javax.swing.JLabel LblProfesionDocente;
    private javax.swing.JLabel LblSeccion;
    private javax.swing.JPanel PnlReaction3;
    private javax.swing.JTable TblCurso;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblreloj;
    // End of variables declaration//GEN-END:variables
}
