/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsDocente;

import Informacion.Docente;
import Informacion.DocentexSecciones;
import Informacion.EstadoPeriodos;
import Informacion.Usuario;
import Informacion.ValoresEstaticos;
import Interfaces.DAODocentexSeccionesImplement;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author medal
 */
public class PanelVerCurso extends javax.swing.JPanel {
    
    Usuario Usua = ValoresEstaticos.Usu;
    Docente DocS = ValoresEstaticos.Doc;
    EstadoPeriodos VEPST = ValoresEstaticos.VEPST;
    DocentexSecciones DxS = new DocentexSecciones();
    DocentexSecciones EDxS = ValoresEstaticos.VEDxS;
    DAODocentexSeccionesImplement DAODxS = new DAODocentexSeccionesImplement();

    /**
     * Creates new form PanelVerCurso
     */
    public PanelVerCurso() {
        initComponents();
        DxS.setDocenteID(Usua.getID());
        DxS.setPeriodoID(VEPST.getIdp());
        EDxS.setDocenteID(DxS.getDocenteID());
        EDxS.setPeriodoID(DxS.getPeriodoID());
        DAODxS.CargarSeccionesdelDocente(DxS, tblVerCursos);
        lblPeriodo.setText(VEPST.getNombrep());
        lblCantCursos.setText(Integer.toString(tblVerCursos.getRowCount()));
    }
    
    class Render extends DefaultTableCellRenderer {
        
        private final JButton button = new JButton("Ver Curso");
        
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            button.setBackground(new Color(55, 156, 22));
            button.setForeground(Color.WHITE);
            return button;
        }
    }
    
    class ButtonEditor extends DefaultCellEditor {
        
        private final JButton button;
        private String label;
        private boolean isPushed;
        
        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);
            button.setBackground(new Color(55, 156, 22));
            button.setForeground(Color.WHITE);
            button.addActionListener(e -> fireEditingStopped());
        }
        
        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            label = "Ver Curso";
            button.setText(label);
            isPushed = true;
            return button;
        }
        
        @Override
        public Object getCellEditorValue() {
            if (isPushed) {
                
                PanelDetallesCurso pDetC = new PanelDetallesCurso();
                mostrarTipo(pDetC);
            }
            isPushed = false;
            return label;
        }
        
        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }
    }
    
    public void mostrarTipo(JPanel j) {
        
        j.setSize(1160, 537);
        j.setLocation(0, 0);
        
        PnlVerCurso.removeAll();
        PnlVerCurso.add(j, BorderLayout.CENTER);
        PnlVerCurso.revalidate();
        PnlVerCurso.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlVerCurso = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        lblCantCursos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVerCursos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        PnlVerCurso.setBackground(new java.awt.Color(0, 153, 204));
        PnlVerCurso.setPreferredSize(new java.awt.Dimension(1160, 537));

        jPanel2.setBackground(new java.awt.Color(153, 102, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ver Cursos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Periodo:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Cursos:");

        lblPeriodo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPeriodo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        lblPeriodo.setPreferredSize(new java.awt.Dimension(150, 50));

        lblCantCursos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCantCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N° Cursos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        lblCantCursos.setPreferredSize(new java.awt.Dimension(150, 50));

        tblVerCursos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        tblVerCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Curso", "Seccion", "Ciclo", "Acción"
            }
        ));
        tblVerCursos.setGridColor(new java.awt.Color(102, 102, 102));
        tblVerCursos.setRowHeight(30);
        tblVerCursos.setShowGrid(true);
        tblVerCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblVerCursosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblVerCursos);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/librito_1.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lapicito.png"))); // NOI18N

        javax.swing.GroupLayout PnlVerCursoLayout = new javax.swing.GroupLayout(PnlVerCurso);
        PnlVerCurso.setLayout(PnlVerCursoLayout);
        PnlVerCursoLayout.setHorizontalGroup(
            PnlVerCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVerCursoLayout.createSequentialGroup()
                .addGroup(PnlVerCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlVerCursoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnlVerCursoLayout.createSequentialGroup()
                        .addGroup(PnlVerCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlVerCursoLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlVerCursoLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblCantCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel4)))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnlVerCursoLayout.setVerticalGroup(
            PnlVerCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlVerCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PnlVerCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlVerCursoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(PnlVerCursoLayout.createSequentialGroup()
                        .addGroup(PnlVerCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlVerCursoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(PnlVerCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCantCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PnlVerCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(PnlVerCursoLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(lblPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PnlVerCursoLayout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(jLabel2)))))
                            .addGroup(PnlVerCursoLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlVerCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlVerCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblVerCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVerCursosMousePressed
        int fila = tblVerCursos.getSelectedRow();
        
        if (fila != -1) {
            String Seccion = tblVerCursos.getValueAt(fila, tblVerCursos.getColumnModel().getColumnIndex("Seccion")).toString();
            String Nombre = tblVerCursos.getValueAt(fila, tblVerCursos.getColumnModel().getColumnIndex("Curso")).toString();
            EDxS.setNroseccionDoc(Integer.parseInt(Seccion));
            EDxS.setNombreCurso(Nombre);

        }
        tblVerCursos.getColumnModel().getColumn(tblVerCursos.getColumnCount() - 1).setCellRenderer(new Render());
        tblVerCursos.getColumnModel().getColumn(tblVerCursos.getColumnCount() - 1).setCellEditor(new ButtonEditor(new JCheckBox()));
    }//GEN-LAST:event_tblVerCursosMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlVerCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantCursos;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JTable tblVerCursos;
    // End of variables declaration//GEN-END:variables
}
