/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames_PanelsDocente;

import DAO.HorarioCicloSeccion;
import Frames_PanelsDocente.*;
import Informacion.Docente;
import Informacion.DocentexSecciones;
import Informacion.EstadoPeriodos;
import Informacion.NotasDetalles;
import Informacion.Usuario;
import Informacion.ValoresEstaticos;
import Interfaces.DAODocentexSeccionesImplement;
import Interfaces.DAONotasDetallesImplement;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author medal
 */
public class RegistroDeNotas extends javax.swing.JFrame {

    Usuario Usua = ValoresEstaticos.Usu;

    EstadoPeriodos VEPST = ValoresEstaticos.VEPST;
    DocentexSecciones DxS = new DocentexSecciones();
    NotasDetalles ND = new NotasDetalles();
    DocentexSecciones EDxS = ValoresEstaticos.VEDxS;
    NotasDetalles END = ValoresEstaticos.VEND;
    DAODocentexSeccionesImplement DAODxS = new DAODocentexSeccionesImplement();
    DAONotasDetallesImplement DAOND = new DAONotasDetallesImplement();

    public RegistroDeNotas() {
        initComponents();

        DxS.setDocenteID(Usua.getID());
        DxS.setPeriodoID(VEPST.getIdp());
        DxS.setNombreCurso(EDxS.getNombreCurso());
        DxS.setNroseccionDoc(EDxS.getNroseccionDoc());
        DxS.setNombreCurso(EDxS.getNombreCurso());
        DxS.setCodAlumno(EDxS.getCodAlumno());
        DxS.setNCMAlumno(EDxS.getNCMAlumno());
        DxS.setNroNotasRegistradasxAlumno(EDxS.getNroNotasRegistradasxAlumno());
        DxS.setNroAlumnos(EDxS.getNroAlumnos());
        DxS.setAlumnoID(EDxS.getAlumnoID());

        LblNmcAlumno.setText(DxS.getNCMAlumno());
        LblCodigoAlumno.setText(DxS.getCodAlumno());
        DxS.setNotasNombresF(EDxS.getNotasNombresF());
        DxS.setNotasPorcentajesF(EDxS.getNotasPorcentajesF());
        DxS.setNotasTiposF(EDxS.getNotasTiposF());
        DxS.setNroNotasRegistradasxAlumno(EDxS.getNroNotasRegistradasxAlumno());
        btnNota1.setText(DxS.getNotasNombres(0));
        btnNota2.setText(DxS.getNotasNombres(1));
        btnNota3.setText(DxS.getNotasNombres(2));
        btnNota4.setText(DxS.getNotasNombres(3));
      
        BloquearBotones();
    }

    public void mostrarTipo(JPanel j) {

        j.setSize(560, 384);
        j.setLocation(0, 0);

        pnlCambio.removeAll();
        pnlCambio.add(j, BorderLayout.CENTER);
        pnlCambio.revalidate();
        pnlCambio.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlGeneral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNota1 = new javax.swing.JButton();
        btnNota2 = new javax.swing.JButton();
        btnNota4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnNota3 = new javax.swing.JButton();
        LblNmcAlumno = new javax.swing.JLabel();
        LblCodigoAlumno = new javax.swing.JLabel();
        pnlCambio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        PnlGeneral.setBackground(new java.awt.Color(0, 153, 204));
        PnlGeneral.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PnlGeneralMouseMoved(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 537));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Notas");

        btnNota1.setBackground(new java.awt.Color(153, 51, 0));
        btnNota1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnNota1.setForeground(new java.awt.Color(255, 255, 255));
        btnNota1.setText("Primera Nota");
        btnNota1.setBorder(null);
        btnNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNota1ActionPerformed(evt);
            }
        });

        btnNota2.setBackground(new java.awt.Color(153, 102, 0));
        btnNota2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnNota2.setForeground(new java.awt.Color(255, 255, 255));
        btnNota2.setText("Segunda Nota");
        btnNota2.setBorder(null);
        btnNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNota2ActionPerformed(evt);
            }
        });

        btnNota4.setBackground(new java.awt.Color(153, 0, 0));
        btnNota4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnNota4.setForeground(new java.awt.Color(255, 255, 255));
        btnNota4.setText("Cuarta Nota");
        btnNota4.setBorder(null);
        btnNota4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNota4ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Aquí podrás registrar las notas de los Alumnos según");

        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("corresponda:");

        btnNota3.setBackground(new java.awt.Color(51, 102, 0));
        btnNota3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnNota3.setForeground(new java.awt.Color(255, 255, 255));
        btnNota3.setText("Tercera Nota");
        btnNota3.setBorder(null);
        btnNota3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNota3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3))
            .addComponent(btnNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addComponent(btnNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNota4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        LblNmcAlumno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNmcAlumno.setForeground(new java.awt.Color(255, 255, 255));
        LblNmcAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumno:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        LblNmcAlumno.setPreferredSize(new java.awt.Dimension(350, 50));

        LblCodigoAlumno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblCodigoAlumno.setForeground(new java.awt.Color(255, 255, 255));
        LblCodigoAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        LblCodigoAlumno.setPreferredSize(new java.awt.Dimension(130, 50));

        pnlCambio.setBackground(new java.awt.Color(0, 153, 204));
        pnlCambio.setPreferredSize(new java.awt.Dimension(560, 384));

        javax.swing.GroupLayout pnlCambioLayout = new javax.swing.GroupLayout(pnlCambio);
        pnlCambio.setLayout(pnlCambioLayout);
        pnlCambioLayout.setHorizontalGroup(
            pnlCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        pnlCambioLayout.setVerticalGroup(
            pnlCambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PnlGeneralLayout = new javax.swing.GroupLayout(PnlGeneral);
        PnlGeneral.setLayout(PnlGeneralLayout);
        PnlGeneralLayout.setHorizontalGroup(
            PnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlGeneralLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(PnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlGeneralLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(PnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblCodigoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblNmcAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        PnlGeneralLayout.setVerticalGroup(
            PnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlGeneralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LblNmcAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LblCodigoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 114, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BloquearBotones() {
        DAODxS.CargarNotasFinalesAlumno(DxS);
        switch (DxS.getNroNotasRegistradasxAlumno()) {
            case 0:
                btnNota2.setEnabled(false);
                btnNota3.setEnabled(false);
                btnNota4.setEnabled(false);
                break;
            case 1:
                btnNota1.setEnabled(false);
                btnNota2.setEnabled(true);
                btnNota3.setEnabled(false);
                btnNota4.setEnabled(false);
                break;
            case 2:
                btnNota1.setEnabled(false);
                btnNota2.setEnabled(false);
                btnNota3.setEnabled(true);
                btnNota4.setEnabled(false);
                break;
            case 3:
                btnNota1.setEnabled(false);
                btnNota2.setEnabled(false);
                btnNota3.setEnabled(false);
                btnNota4.setEnabled(true);
                break;
            case 4:
                btnNota1.setEnabled(false);
                btnNota2.setEnabled(false);
                btnNota3.setEnabled(false);
                btnNota4.setEnabled(false);
                this.dispose();
                break;
            default:
                break;
        }
    }

    public void DefinirPanel(int valor) {
        ND.setAlumnoID(DxS.getAlumnoID());
        ND.setNombrenota(DxS.getNotasNombres(valor));
        ND.setNroNota(valor + 1);
        ND.setNroseccionDoc(DxS.getNroseccionDoc());
        ND.setPorcentaje(DxS.getNotasPorcentajes(valor));
        END.setAlumnoID(ND.getAlumnoID());
        END.setNombrenota(ND.getNombrenota());
        END.setNroNota(valor + 1);
        END.setNroseccionDoc(ND.getNroseccionDoc());
        END.setPorcentaje(ND.getPorcentaje());
        switch (DxS.getNotasTipos(valor)) {
            case "Unica":
                ND.setTipoNota("Unica");
                END.setTipoNota(ND.getTipoNota());
                PanelNotaUnica pNotaU = new PanelNotaUnica();
                mostrarTipo(pNotaU);
                break;
            case "Promedio":

                ND.setTipoNota("Promedio");
                END.setTipoNota(ND.getTipoNota());
                PanelPromedio pProm = new PanelPromedio();
                mostrarTipo(pProm);
                break;
            case "Participacion":

                ND.setTipoNota("Participacion");
                END.setTipoNota(ND.getTipoNota());
                PanelParticipacion pPart = new PanelParticipacion();
                mostrarTipo(pPart);
                break;
            default:
                break;
        }
    }
    private void btnNota4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNota4ActionPerformed
        DefinirPanel(3);
    }//GEN-LAST:event_btnNota4ActionPerformed

    private void btnNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNota1ActionPerformed
        DefinirPanel(0);
    }//GEN-LAST:event_btnNota1ActionPerformed

    private void btnNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNota2ActionPerformed
        DefinirPanel(1);
    }//GEN-LAST:event_btnNota2ActionPerformed

    private void btnNota3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNota3ActionPerformed
        DefinirPanel(2);
    }//GEN-LAST:event_btnNota3ActionPerformed

    private void PnlGeneralMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PnlGeneralMouseMoved
     
    }//GEN-LAST:event_PnlGeneralMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCodigoAlumno;
    private javax.swing.JLabel LblNmcAlumno;
    private javax.swing.JPanel PnlGeneral;
    private javax.swing.JButton btnNota1;
    private javax.swing.JButton btnNota2;
    private javax.swing.JButton btnNota3;
    private javax.swing.JButton btnNota4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlCambio;
    // End of variables declaration//GEN-END:variables
}
