/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames_PanelsGenerales;

import Frames_PanelsGestor.TbAlumnosActivos;
import AA_IniciarPrograma.Login;
import Frames_PanelsAlumno.PanelDetallesCurso;
import Frames_PanelsAlumno.PanelEmpezarmatricula;
import Frames_PanelsAlumno.PanelRecordNotas;
import Frames_PanelsGestor.PanelConfiguracionPeriodo;
import Frames_PanelsGestor.TbDocentesActivos;
import Frames_PanelsDocente.PanelSolCambioDocente;
import Frames_PanelsDocente.PanelVerCurso;
import Informacion.EstadoPeriodos;
import Informacion.Usuario;
import Informacion.ValoresEstaticos;
import Interfaces.Estados;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Frames_PanelsGestor.PanelRevisarSol;
import Frames_PanelsAlumno.PanelSolRetiroCurso;

/**
 *
 * @author USUARIO
 */
public class MenuGeneral extends javax.swing.JFrame {

    Usuario Usua = ValoresEstaticos.Usu;
    EstadoPeriodos VEPST = ValoresEstaticos.VEPST;
    Estados E = new Estados();

    /**
     * Creates new form PanelGeneral
     */
    public MenuGeneral() {
        initComponents();
        this.setLocationRelativeTo(null);

        initRoles(Usua.getRol());
    }

    public void mostrarTipo(JPanel j) {

        j.setSize(1160, 537);
        j.setLocation(0, 0);

        PnlBase.removeAll();
        PnlBase.add(j, BorderLayout.CENTER);
        PnlBase.revalidate();
        PnlBase.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFondo = new javax.swing.JPanel();
        PnlBase = new javax.swing.JPanel();
        BtnCerrar = new javax.swing.JButton();
        BtnOpc1 = new javax.swing.JButton();
        BtnOpc2 = new javax.swing.JButton();
        BtnOpc3 = new javax.swing.JButton();
        BtnOpc4 = new javax.swing.JButton();
        BtnOpc5 = new javax.swing.JButton();
        BtnOpc6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 607));

        PnlFondo.setBackground(new java.awt.Color(0, 153, 255));
        PnlFondo.setMinimumSize(new java.awt.Dimension(1160, 607));

        PnlBase.setBackground(new java.awt.Color(57, 91, 126));
        PnlBase.setPreferredSize(new java.awt.Dimension(1160, 537));

        javax.swing.GroupLayout PnlBaseLayout = new javax.swing.GroupLayout(PnlBase);
        PnlBase.setLayout(PnlBaseLayout);
        PnlBaseLayout.setHorizontalGroup(
            PnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PnlBaseLayout.setVerticalGroup(
            PnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        BtnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        BtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cerrarsesion32x32.png"))); // NOI18N
        BtnCerrar.setBorder(null);
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        BtnOpc1.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc1.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc1.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verotros32x32.png"))); // NOI18N
        BtnOpc1.setText("Opcion 1");
        BtnOpc1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc1.setBorderPainted(false);
        BtnOpc1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc1.setIconTextGap(15);
        BtnOpc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc1ActionPerformed(evt);
            }
        });

        BtnOpc2.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc2.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc2.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verotros32x32.png"))); // NOI18N
        BtnOpc2.setText("Opcion 2");
        BtnOpc2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc2.setBorderPainted(false);
        BtnOpc2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc2.setIconTextGap(15);
        BtnOpc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc2ActionPerformed(evt);
            }
        });

        BtnOpc3.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc3.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc3.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verotros32x32.png"))); // NOI18N
        BtnOpc3.setText("Opcion 3");
        BtnOpc3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc3.setBorderPainted(false);
        BtnOpc3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc3.setIconTextGap(15);
        BtnOpc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc3ActionPerformed(evt);
            }
        });

        BtnOpc4.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc4.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc4.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verotros32x32.png"))); // NOI18N
        BtnOpc4.setText("Opcion 4");
        BtnOpc4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc4.setBorderPainted(false);
        BtnOpc4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc4.setIconTextGap(15);
        BtnOpc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc4ActionPerformed(evt);
            }
        });

        BtnOpc5.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc5.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc5.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verotros32x32.png"))); // NOI18N
        BtnOpc5.setText("Opcion 5");
        BtnOpc5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc5.setBorderPainted(false);
        BtnOpc5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc5.setIconTextGap(15);
        BtnOpc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc5ActionPerformed(evt);
            }
        });

        BtnOpc6.setBackground(new java.awt.Color(17, 17, 103));
        BtnOpc6.setFont(new java.awt.Font("Lucida Console", 1, 10)); // NOI18N
        BtnOpc6.setForeground(new java.awt.Color(255, 255, 255));
        BtnOpc6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/verotros32x32.png"))); // NOI18N
        BtnOpc6.setText("Opcion 1");
        BtnOpc6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(0, 0, 0)));
        BtnOpc6.setBorderPainted(false);
        BtnOpc6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnOpc6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnOpc6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnOpc6.setIconTextGap(15);
        BtnOpc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpc6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlFondoLayout = new javax.swing.GroupLayout(PnlFondo);
        PnlFondo.setLayout(PnlFondoLayout);
        PnlFondoLayout.setHorizontalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addComponent(BtnOpc1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnOpc6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BtnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
            .addComponent(PnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PnlFondoLayout.setVerticalGroup(
            PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFondoLayout.createSequentialGroup()
                .addGroup(PnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnOpc6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(PnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOpc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc1ActionPerformed
        // TODO add your handling code here:
        switch (Usua.getRol()) {
            case "Administrador":

                if (VEPST.getEstadop().equals("Prematricula") || VEPST.getEstadop().equals("Matricula Abierta")) {
                    PanelRegistrarCursos pC = new PanelRegistrarCursos();
                    mostrarTipo(pC);
                } else {
                    if (E.LlamarPeriodosRegistrables() > 0) {
                        PanelRegistrarCursos pC = new PanelRegistrarCursos();
                        mostrarTipo(pC);
                    } else {
                        JOptionPane.showMessageDialog(null, "No hay periodos habilitados para Registrar Cursos");
                    }

                }
                break;
            case "Docente":
                if (VEPST.getEstadop().equals("Finalizado") || VEPST.getEstadop().equals("En Curso") || VEPST.getEstadop().equals("Matricula Abierta")) {
                    PanelVerCurso PVC = new PanelVerCurso();
                    mostrarTipo(PVC);
                } else {
                    JOptionPane.showMessageDialog(null, "Aun no inicia el ciclo actual, no puede ver sus cursos por ahora");
                }

                break;
            case "Alumno":
                if (VEPST.getEstadop().equals("Matricula Abierta")) {
                    PanelEmpezarmatricula PEM = new PanelEmpezarmatricula();
                    mostrarTipo(PEM);
                } else {
                    JOptionPane.showMessageDialog(null, "Matriculas cerradas por ahora");
                }

                break;

            default:
                System.out.println("ERROR");
        }

    }//GEN-LAST:event_BtnOpc1ActionPerformed

    private void BtnOpc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc2ActionPerformed

        switch (Usua.getRol()) {
            case "Administrador":

                if (VEPST.getEstadop().equals("Prematricula") || VEPST.getEstadop().equals("Matricula Abierta")) {
                    Registro irReg = new Registro();
                    irReg.setVisible(true);
                    this.setEnabled(false);
                    irReg.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosed(WindowEvent e) {
                            setEnabled(true); // Habilitar la ventana principal cuando la ventana secundaria se cierra
                        }

                        public void windowDispose(WindowEvent e) {
                            setEnabled(true);
                        }
                    });
                } else {

                    JOptionPane.showMessageDialog(null, "El periodo actual no se encuentra habilitado para registrar usuarios");

                }

                break;
            case "Docente":
                if (VEPST.getEstadop().equals("En Curso") || VEPST.getEstadop().equals("Matricula Abierta")) {
                    PanelSolCambioDocente PSolD = new PanelSolCambioDocente();
                    mostrarTipo(PSolD);
                } else {

                    JOptionPane.showMessageDialog(null, "El periodo actual no se encuentra habilitado para solicitar un cambio");

                }

                break;
            case "Alumno":

                PanelDetallesCurso PDCA = new PanelDetallesCurso();
                mostrarTipo(PDCA);

                break;

            default:
                System.out.println("ERROR");
        }


    }//GEN-LAST:event_BtnOpc2ActionPerformed

    private void BtnOpc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc3ActionPerformed
        switch (Usua.getRol()) {
            case "Administrador":
                TbAlumnosActivos TAA = new TbAlumnosActivos();
                mostrarTipo(TAA);
                break;
            case "Docente":
                HorarioSemanal HSD = new HorarioSemanal();
                mostrarTipo(HSD);
                break;
            case "Alumno":
                HorarioSemanal HSA = new HorarioSemanal();
                mostrarTipo(HSA);
                break;

            default:
                System.out.println("ERROR");
        }
    }//GEN-LAST:event_BtnOpc3ActionPerformed

    private void BtnOpc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc4ActionPerformed
        switch (Usua.getRol()) {
            case "Administrador":
                TbDocentesActivos TDA = new TbDocentesActivos();
                mostrarTipo(TDA);
                break;
            case "Docente":
                JOptionPane.showMessageDialog(null, "Opcion no Habilitada");
                break;
            case "Alumno":
                if (VEPST.getEstadop().equals("En Curso")) {
                    PanelSolRetiroCurso PSR = new PanelSolRetiroCurso();
                    mostrarTipo(PSR);
                } else {

                    JOptionPane.showMessageDialog(null, "El periodo actual no se encuentra habilitado para solicitar un retiro");

                }

                break;

            default:
                System.out.println("ERROR");
        }
    }//GEN-LAST:event_BtnOpc4ActionPerformed

    private void BtnOpc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc5ActionPerformed
        switch (Usua.getRol()) {
            case "Administrador":
                if (VEPST.getEstadop().equals("En Curso") || VEPST.getEstadop().equals("Matricula Abierta")) {
                    PanelRevisarSol PRS = new PanelRevisarSol();
                    mostrarTipo(PRS);
                } else {
                    JOptionPane.showMessageDialog(null, "El periodo actual no se encuentra habilitado para procesar solicitudes");
                }
                break;
            case "Docente":
                CambiarInformacion PCI = new CambiarInformacion();
                mostrarTipo(PCI);
                break;
            case "Alumno":
                CambiarInformacion PCI1 = new CambiarInformacion();
                mostrarTipo(PCI1);
                break;

            default:
                System.out.println("ERROR");
        }
    }//GEN-LAST:event_BtnOpc5ActionPerformed

    private void BtnOpc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpc6ActionPerformed
        switch (Usua.getRol()) {
            case "Administrador":
                PanelConfiguracionPeriodo pP = new PanelConfiguracionPeriodo();
                mostrarTipo(pP);
                break;
            case "Docente":

                break;
            case "Alumno":
                PanelRecordNotas pRN = new PanelRecordNotas();
                mostrarTipo(pRN);
                break;

            default:
                System.out.println("ERROR");
        }


    }//GEN-LAST:event_BtnOpc6ActionPerformed

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Quieres cerrar sesión?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            Login L = new Login();
            L.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void initRoles(String Roles) {
        switch (Roles) {
            case "Administrador":
                BtnOpc1.setText("Registrar Cursos");
                BtnOpc2.setText("Registrar Usuarios");
                BtnOpc3.setText("Ver Alumnos activos");
                BtnOpc4.setText("Ver Docentes activos");
                BtnOpc5.setText("Procesar solicitudes");
                BtnOpc6.setText("Cambiar Estados");
                /* BtnOpc4.setEnabled(false);
                BtnOpc4.setVisible(false);
                BtnOpc5.setEnabled(false);
                BtnOpc5.setVisible(false);
                BtnOpc6.setEnabled(false);
                BtnOpc6.setVisible(false);
                //  Setear Color del Menu
            PnlBackGround.setBackground(new Color(247, 210, 210));
                PnlContenido.setBackground(new Color(247, 210, 210));
                PnlTitulo.setBackground(new Color(201, 31, 31));
                PnlOpciones.setBackground(new Color(198, 0, 0));*/
                BtnOpc1.setBackground(new Color(21, 106, 193));
                BtnOpc2.setBackground(new Color(21, 106, 193));
                BtnOpc3.setBackground(new Color(21, 106, 193));
                BtnOpc4.setBackground(new Color(21, 106, 193));
                BtnOpc5.setBackground(new Color(21, 106, 193));
                BtnOpc6.setBackground(new Color(21, 106, 193));
                //LblImagenUsuario.setIcon(new ImageIcon(getClass().getResource("/IconoUser100x100rojo.png")));
                BtnOpc1.setIcon(new ImageIcon(getClass().getResource("/resources/vercursos.png")));
                BtnOpc2.setIcon(new ImageIcon(getClass().getResource("/resources/registrarusu.png")));
                BtnOpc3.setIcon(new ImageIcon(getClass().getResource("/resources/veralumnos.png")));
                BtnOpc4.setIcon(new ImageIcon(getClass().getResource("/resources/verdocentes.png")));
                BtnOpc5.setIcon(new ImageIcon(getClass().getResource("/resources/versolis.png")));
                BtnOpc6.setIcon(new ImageIcon(getClass().getResource("/resources/relojestados.png")));
                break;
            case "Docente":
                BtnOpc1.setText("Ver Cursos");
                BtnOpc2.setText("Hacer Solicitudes");
                BtnOpc3.setText("Horario Semanal");
                BtnOpc4.setText("Reportes de Notas");
                BtnOpc5.setText("Informacion");
                BtnOpc6.setText("Inhabilitado");
                BtnOpc6.setEnabled(false);
                /* BtnOpc4.setEnabled(false);
                BtnOpc4.setVisible(false);
                BtnOpc5.setEnabled(false);
                BtnOpc5.setVisible(false);
                BtnOpc6.setEnabled(false);
                BtnOpc6.setVisible(false);
                //  Setear Color del Menu
            PnlBackGround.setBackground(new Color(247, 210, 210));
                PnlContenido.setBackground(new Color(247, 210, 210));
                PnlTitulo.setBackground(new Color(201, 31, 31));
                PnlOpciones.setBackground(new Color(198, 0, 0));*/
                PnlBase.setBackground(new Color(0, 153, 204));
                BtnOpc1.setBackground(new Color(120, 40, 238));
                BtnOpc2.setBackground(new Color(120, 40, 238));
                BtnOpc3.setBackground(new Color(120, 40, 238));
                BtnOpc4.setBackground(new Color(120, 40, 238));
                BtnOpc5.setBackground(new Color(120, 40, 238));
                BtnOpc6.setBackground(new Color(51, 51, 51));
                //LblImagenUsuario.setIcon(new ImageIcon(getClass().getResource("/IconoUser100x100rojo.png")));
                BtnOpc1.setIcon(new ImageIcon(getClass().getResource("/resources/librito.png")));
                BtnOpc2.setIcon(new ImageIcon(getClass().getResource("/resources/hacerSolicitudesRend32x32.png")));
                BtnOpc3.setIcon(new ImageIcon(getClass().getResource("/resources/horario.png")));
                BtnOpc4.setIcon(new ImageIcon(getClass().getResource("/resources/vernotas.png")));
                BtnOpc5.setIcon(new ImageIcon(getClass().getResource("/resources/informacion.png")));
                BtnOpc6.setIcon(new ImageIcon(getClass().getResource("/resources/locked.png")));
                break;
            case "Alumno":
                BtnOpc1.setText("Empezar Matricula");
                BtnOpc2.setText("Cursos Matriculados");
                BtnOpc3.setText("Horario Semanal");
                BtnOpc4.setText("Solicitar SAE");
                BtnOpc5.setText("Informacion");
                BtnOpc6.setText("RecordNotas");

                PnlBase.setBackground(new Color(0, 102, 51));
                BtnOpc1.setBackground(new Color(102, 0, 51));
                BtnOpc2.setBackground(new Color(102, 0, 51));
                BtnOpc3.setBackground(new Color(102, 0, 51));
                BtnOpc4.setBackground(new Color(102, 0, 51));
                BtnOpc5.setBackground(new Color(102, 0, 51));
                BtnOpc6.setBackground(new Color(102, 0, 51));
                BtnOpc2.setIcon(new ImageIcon(getClass().getResource("/resources/librito.png")));
                BtnOpc3.setIcon(new ImageIcon(getClass().getResource("/resources/horario.png")));
                BtnOpc6.setIcon(new ImageIcon(getClass().getResource("/resources/informacion.png")));
                break;
            default:
                JOptionPane.showMessageDialog(null, "ERROR 876121: Contacte con Soporte Tecnico");
                break;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnOpc1;
    private javax.swing.JButton BtnOpc2;
    private javax.swing.JButton BtnOpc3;
    private javax.swing.JButton BtnOpc4;
    private javax.swing.JButton BtnOpc5;
    private javax.swing.JButton BtnOpc6;
    private javax.swing.JPanel PnlBase;
    private javax.swing.JPanel PnlFondo;
    // End of variables declaration//GEN-END:variables
}
