/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsGenerales;

import Frames_PanelsGestor.PanelConfiguracionPeriodo;
import Informacion.Docente;
import Informacion.Horario;
import Informacion.Secciones;
import Informacion.ValoresEstaticos;
import Interfaces.DAODocente;
import Interfaces.DAODocenteImplement;
import Interfaces.DAOHorarioImplement;
import Interfaces.DAOSeccionesImplement;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.JSlider;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Personal
 */
public class PanelRegistroHorario extends javax.swing.JPanel {

    String listadias[] = new String[2];
    String listaturnos[] = new String[2];
    Secciones S = new Secciones();
    Secciones Secca = ValoresEstaticos.VES;
    Horario H = new Horario();
    Docente D = new Docente();
    DAOSeccionesImplement DAOs = new DAOSeccionesImplement();
    DAOHorarioImplement DAOh = new DAOHorarioImplement();
    DAODocenteImplement DAOd = new DAODocenteImplement();
    int sesiones;

    public PanelRegistroHorario() {
        initComponents();

        LblCurso.setText(Secca.getNombreSeccion());
        LblSeccion.setText(Integer.toString(Secca.getSeccionID()));
        sesiones = DAOs.obtenerSesiones(S);
        LblNroSesiones.setText(Integer.toString(sesiones));
        if (sesiones == 1) {
            SldSesion2.setEnabled(false);
            CmbSesion2.setEnabled(false);
            listadias[1] = "nada";
            listaturnos[1] = "nada";
        }
        CmbDocente.setEnabled(false);
        BtnRegHorario.setEnabled(false);
    }

    private void mostrarTipo(JPanel j) {

        j.setSize(1160, 537);
        j.setLocation(0, 0);

        PnlRegHorario.removeAll();
        PnlRegHorario.add(j, BorderLayout.CENTER);
        PnlRegHorario.revalidate();
        PnlRegHorario.repaint();
    }

    private void CargarTabla(JTable tabla) {
        DefaultTableModel modeloTablacurso = (DefaultTableModel) tabla.getModel();

        modeloTablacurso.addRow(new Object[]{
            "Diurno", AsignarX(1, "diurno"), AsignarX(2, "diurno"), AsignarX(3, "diurno"), AsignarX(4, "diurno"), AsignarX(5, "diurno"), AsignarX(6, "diurno")
        });

        modeloTablacurso.addRow(new Object[]{
            "Nocturno", AsignarX(1, "nocturno"), AsignarX(2, "nocturno"), AsignarX(3, "nocturno"), AsignarX(4, "nocturno"), AsignarX(5, "nocturno"), AsignarX(6, "nocturno")
        });

    }

    private void LimpiarTabla(JTable tabla) {
        DefaultTableModel modeloTablacurso = (DefaultTableModel) tabla.getModel();
        int filas = modeloTablacurso.getRowCount();
        for (int i = 0; i < filas; i++) {

            modeloTablacurso.removeRow(0);
        }
    }

    private String AsignarX(int i, String turno) {
        String valor = "";
        String turnoreal1, turnoreal2;
        turnoreal1 = (String) CmbSesion1.getSelectedItem();
        turnoreal2 = (String) CmbSesion2.getSelectedItem();
        if (sesiones == 1) {
            if (turno.equals(turnoreal1)) {
                if (i == (int) SldSesion1.getValue()) {
                    valor = "X";
                }
            }
        } else {
            if (turno.equals(turnoreal1)) {
                if (i == (int) SldSesion1.getValue()) {
                    valor = "X";
                }

            }
            if (turno.equals(turnoreal2)) {
                if (i == (int) SldSesion2.getValue()) {
                    valor = "X";
                }

            }
        }

        return valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlRegHorario = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblCurso = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblDocente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LblCurso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblSeccion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CmbSesion1 = new javax.swing.JComboBox<>();
        CmbSesion2 = new javax.swing.JComboBox<>();
        SldSesion1 = new javax.swing.JSlider();
        SldSesion2 = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LblNroSesiones = new javax.swing.JLabel();
        CmbDocente = new javax.swing.JComboBox<>();
        BtnBuscarDocente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        LblNombreDocente = new javax.swing.JLabel();
        LblProfesionDocente = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BtnRegHorario = new javax.swing.JButton();
        lblreloj = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1160, 537));

        PnlRegHorario.setBackground(new java.awt.Color(57, 91, 126));
        PnlRegHorario.setPreferredSize(new java.awt.Dimension(1160, 537));

        jPanel2.setBackground(new java.awt.Color(16, 122, 149));
        jPanel2.setPreferredSize(new java.awt.Dimension(1160, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(411, 56));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Horarios");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 12, 412, 52));

        TblCurso.setAutoCreateRowSorter(true);
        TblCurso.setBackground(new java.awt.Color(0, 0, 0));
        TblCurso.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 0)));
        TblCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TblCurso.setForeground(new java.awt.Color(255, 0, 51));
        TblCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turno", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TblCurso.setGridColor(new java.awt.Color(255, 255, 255));
        TblCurso.setSelectionForeground(new java.awt.Color(242, 242, 209));
        TblCurso.setShowGrid(true);
        jScrollPane1.setViewportView(TblCurso);

        TblDocente.setAutoCreateRowSorter(true);
        TblDocente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        TblDocente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TblDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Diurno", null, null, null, null, null, null},
                {"Nocturno", null, null, null, null, null, null}
            },
            new String [] {
                "Turno", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"
            }
        ));
        TblDocente.setToolTipText("");
        TblDocente.setGridColor(new java.awt.Color(204, 204, 0));
        TblDocente.setSelectionForeground(new java.awt.Color(242, 242, 209));
        TblDocente.setShowGrid(true);
        jScrollPane2.setViewportView(TblDocente);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setForeground(new java.awt.Color(0, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 105));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vista del Curso: ");

        LblCurso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblCurso.setForeground(new java.awt.Color(255, 255, 255));
        LblCurso.setText("-");
        LblCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        LblCurso.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vista de la Sección:");

        LblSeccion.setForeground(new java.awt.Color(255, 255, 255));
        LblSeccion.setText("-");
        LblSeccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        LblSeccion.setPreferredSize(new java.awt.Dimension(180, 50));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Turnos :");

        CmbSesion1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CmbSesion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "diurno", "nocturno" }));
        CmbSesion1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sesion 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        CmbSesion1.setPreferredSize(new java.awt.Dimension(180, 50));
        CmbSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbSesion1ActionPerformed(evt);
            }
        });

        CmbSesion2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CmbSesion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "diurno", "nocturno" }));
        CmbSesion2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sesion 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        CmbSesion2.setPreferredSize(new java.awt.Dimension(180, 50));

        SldSesion1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        SldSesion1.setMajorTickSpacing(1);
        SldSesion1.setMaximum(6);
        SldSesion1.setMinimum(1);
        SldSesion1.setMinorTickSpacing(1);
        SldSesion1.setPaintLabels(true);
        SldSesion1.setPaintTicks(true);
        SldSesion1.setSnapToTicks(true);
        SldSesion1.setToolTipText("");
        SldSesion1.setFocusTraversalPolicyProvider(true);
        SldSesion1.setFocusable(false);

        SldSesion2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        SldSesion2.setMajorTickSpacing(1);
        SldSesion2.setMaximum(6);
        SldSesion2.setMinimum(1);
        SldSesion2.setMinorTickSpacing(1);
        SldSesion2.setPaintLabels(true);
        SldSesion2.setPaintTicks(true);
        SldSesion2.setSnapToTicks(true);
        SldSesion2.setToolTipText("");
        SldSesion2.setFocusTraversalPolicyProvider(true);
        SldSesion2.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SldSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SldSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CmbSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(LblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CmbSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SldSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CmbSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SldSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setForeground(new java.awt.Color(0, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 105));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seleccione al Docente:");

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Número de Sesiones:");

        LblNroSesiones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNroSesiones.setForeground(new java.awt.Color(255, 255, 255));
        LblNroSesiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNroSesiones.setText("-");
        LblNroSesiones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sesión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        LblNroSesiones.setPreferredSize(new java.awt.Dimension(110, 50));

        CmbDocente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CmbDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12))); // NOI18N
        CmbDocente.setPreferredSize(new java.awt.Dimension(180, 50));
        CmbDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbDocenteActionPerformed(evt);
            }
        });

        BtnBuscarDocente.setBackground(new java.awt.Color(204, 102, 0));
        BtnBuscarDocente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnBuscarDocente.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarDocente.setText("Buscar Docente");
        BtnBuscarDocente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnBuscarDocente.setPreferredSize(new java.awt.Dimension(110, 25));
        BtnBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarDocenteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscador de Disponibilidad del Docente:");

        LblNombreDocente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNombreDocente.setForeground(new java.awt.Color(255, 255, 255));
        LblNombreDocente.setText("-");
        LblNombreDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre Completo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        LblNombreDocente.setPreferredSize(new java.awt.Dimension(180, 50));

        LblProfesionDocente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblProfesionDocente.setForeground(new java.awt.Color(255, 255, 255));
        LblProfesionDocente.setText("-");
        LblProfesionDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profesión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        LblProfesionDocente.setPreferredSize(new java.awt.Dimension(180, 50));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(BtnBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblNroSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CmbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(33, 33, 33))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNombreDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblProfesionDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNroSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(BtnBuscarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblProfesionDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Docente");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(64, 64, 64))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 51, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Curso");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel11)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnRegHorario.setBackground(new java.awt.Color(255, 0, 0));
        BtnRegHorario.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BtnRegHorario.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegHorario.setText("Registrar Horario");
        BtnRegHorario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnRegHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegHorarioActionPerformed(evt);
            }
        });

        lblreloj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/horar.png"))); // NOI18N

        javax.swing.GroupLayout PnlRegHorarioLayout = new javax.swing.GroupLayout(PnlRegHorario);
        PnlRegHorario.setLayout(PnlRegHorarioLayout);
        PnlRegHorarioLayout.setHorizontalGroup(
            PnlRegHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PnlRegHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                        .addComponent(lblreloj, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(BtnRegHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PnlRegHorarioLayout.setVerticalGroup(
            PnlRegHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(PnlRegHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                        .addGroup(PnlRegHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegHorarioLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblreloj, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(BtnRegHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlRegHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlRegHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarDocenteActionPerformed
        CmbDocente.removeAllItems();
        listaturnos[0] = (String) CmbSesion1.getSelectedItem();
        TransformarSlider(SldSesion1, 0);
        if (sesiones == 2) {
            TransformarSlider(SldSesion2, 1);
            listaturnos[1] = (String) CmbSesion2.getSelectedItem();
        }
        H.setDiasemana(listadias);
        H.setTurno(listaturnos);
        if (listaturnos[0].equals(listaturnos[1]) && listadias[0].equals(listadias[1])) {
            JOptionPane.showMessageDialog(null, "No puede registrar dos sesiones totalmente iguales");
            CmbDocente.setEnabled(false);
            LimpiarTabla(TblCurso);

        } else {
            int valor = DAOh.CargarDocentesxHorario(H, CmbDocente);

            if (valor > 0) {

                LimpiarTabla(TblCurso);
                CargarTabla(TblCurso);
                BtnRegHorario.setEnabled(true);
                CmbDocente.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "No hay docentes disponibles");
                BtnRegHorario.setEnabled(false);
                CmbDocente.setEnabled(false);
            }
        }

    }//GEN-LAST:event_BtnBuscarDocenteActionPerformed

    private void BtnRegHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegHorarioActionPerformed
        Secca.setCodigoDocenteSeccion((String) CmbDocente.getSelectedItem());
        //System.out.println("antes igualar codigousu: " + Secca.getCodigoDocenteSeccion());
        DAOh.RegistrarHorario(H, 0);
        //System.out.println("Pasó Registro de Horario 1");
        if (sesiones == 2) {
            DAOh.RegistrarHorario(H, 1);
            //  System.out.println("Pasó Registro de Horario 2");
        }
        for (int i = 0; i < 4; i++) {
            DAOs.registrarFormatNotas(Secca, i);
        }
        //System.out.println("Pasó RegistrodeFormat");
        DAOs.registrarSeccion(Secca, H);
        PanelRegistrarCursos pC = new PanelRegistrarCursos();
        mostrarTipo(pC);
        //System.out.println("Pasó TODO");
    }//GEN-LAST:event_BtnRegHorarioActionPerformed

    private void CmbSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbSesion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbSesion1ActionPerformed

    private void CmbDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbDocenteActionPerformed

        if (CmbDocente.getItemCount() > 0) {
            D.setCodigoUsu((String) CmbDocente.getSelectedItem());
            DAOd.DefinirDocente(D);
            LblNombreDocente.setText(D.getNombrecompleto());
            LblProfesionDocente.setText(D.getEspecializacion());

        } else {
            LblNombreDocente.setText("-");
            LblProfesionDocente.setText("-");
        }

    }//GEN-LAST:event_CmbDocenteActionPerformed

    private void TransformarSlider(JSlider JS, int orden) {
        int opc;
        opc = (int) JS.getValue();
        switch (opc) {
            case 1:
                listadias[orden] = "lunes";
                break;
            case 2:
                listadias[orden] = "martes";
                break;
            case 3:
                listadias[orden] = "miercoles";
                break;
            case 4:
                listadias[orden] = "jueves";
                break;
            case 5:
                listadias[orden] = "viernes";
                break;
            case 6:
                listadias[orden] = "sabado";
                break;
            default:
                throw new AssertionError();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarDocente;
    private javax.swing.JButton BtnRegHorario;
    private javax.swing.JComboBox<String> CmbDocente;
    private javax.swing.JComboBox<String> CmbSesion1;
    private javax.swing.JComboBox<String> CmbSesion2;
    private javax.swing.JLabel LblCurso;
    private javax.swing.JLabel LblNombreDocente;
    private javax.swing.JLabel LblNroSesiones;
    private javax.swing.JLabel LblProfesionDocente;
    private javax.swing.JLabel LblSeccion;
    private javax.swing.JPanel PnlRegHorario;
    private javax.swing.JSlider SldSesion1;
    private javax.swing.JSlider SldSesion2;
    private javax.swing.JTable TblCurso;
    private javax.swing.JTable TblDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblreloj;
    // End of variables declaration//GEN-END:variables
}
