/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsGenerales;
//Ojooooo
//Falta llenar periodo, no sé cómo hacerlo

import Informacion.EstadoPeriodos;
import Informacion.Secciones;
import Informacion.ValoresEstaticos;

import Interfaces.DAOSeccionesImplement;
import Interfaces.Estados;
import java.awt.BorderLayout;

import javax.swing.JComboBox;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import javax.swing.JTextField;

/**
 *
 * @author Personal
 */
public class PanelRegistrarCursos extends javax.swing.JPanel {

    DAOSeccionesImplement DAOs = new DAOSeccionesImplement();
    Secciones Secca = ValoresEstaticos.VES;
    Secciones S = new Secciones();
    int valCiclo = 0;

    String listaS[] = new String[4];
    int listaI[] = new int[4];
    Estados E = new Estados();

    /**
     * Creates new form RegistrarCursos
     */
    public PanelRegistrarCursos() {
        initComponents();
        E.DefinirPeriodo();
        LblPeriodoActual.setText(E.LlamarNamePeriodosRegistrables());
        GenerarSeccion();
        cargarCiclos(cmbCiclo);
        S.setCicloSeccion((int) cmbCiclo.getSelectedItem());
        DAOs.cargar(S, CmbCurso);
        S.setNombreSeccion((String) CmbCurso.getSelectedItem());
        valCiclo = 1;

        LblSeccion.setText(Integer.toString(S.getSeccionID()));
        Secca.setNotasTip(0, "Unica");
        Secca.setNotasTip(1, "Unica");
        Secca.setNotasTip(2, "Unica");
        Secca.setNotasTip(3, "Unica");
    }

    public void mostrarTipo(JPanel j) {

        j.setSize(1160, 537);
        j.setLocation(0, 0);

        PnlRegCurso.removeAll();
        PnlRegCurso.add(j, BorderLayout.CENTER);
        PnlRegCurso.revalidate();
        PnlRegCurso.repaint();
    }

    public void Limpiar(JTextField texto) {
        texto.setText("");
    }

    private void cargarCiclos(JComboBox cmb) {
        for (int i = 1; i <= 12; i++) {
            cmb.addItem(i);
        }
    }

    private boolean sonElementosIguales(String[] arreglo) {
        for (int i = 0; i < arreglo.length - 1; i++) {
            for (int j = i + 1; j < arreglo.length; j++) {
                if (arreglo[i].equals(arreglo[j])) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroup1 = new javax.swing.ButtonGroup();
        BtnGroup2 = new javax.swing.ButtonGroup();
        BtnGroup3 = new javax.swing.ButtonGroup();
        BtnGroup4 = new javax.swing.ButtonGroup();
        PnlRegCurso = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LblPeriodoActual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CmbCurso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbCiclo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        txtNota4 = new javax.swing.JTextField();
        Lbltipo1 = new javax.swing.JLabel();
        sp1 = new javax.swing.JSpinner();
        sp2 = new javax.swing.JSpinner();
        sp3 = new javax.swing.JSpinner();
        sp4 = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        LblSeccion = new javax.swing.JLabel();
        RBtnUnica1 = new javax.swing.JRadioButton();
        RBtnProm1 = new javax.swing.JRadioButton();
        RBtnPart1 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        Lbltipo2 = new javax.swing.JLabel();
        Lbltipo3 = new javax.swing.JLabel();
        RBtnUnica2 = new javax.swing.JRadioButton();
        RBtnPart2 = new javax.swing.JRadioButton();
        RBtnProm2 = new javax.swing.JRadioButton();
        RBtnUnica3 = new javax.swing.JRadioButton();
        RBtnPart3 = new javax.swing.JRadioButton();
        RBtnProm3 = new javax.swing.JRadioButton();
        RBtnUnica4 = new javax.swing.JRadioButton();
        RBtnPart4 = new javax.swing.JRadioButton();
        RBtnProm4 = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(1160, 537));

        PnlRegCurso.setBackground(new java.awt.Color(57, 91, 126));
        PnlRegCurso.setMinimumSize(new java.awt.Dimension(0, 0));
        PnlRegCurso.setPreferredSize(new java.awt.Dimension(1160, 537));

        jPanel2.setBackground(new java.awt.Color(16, 122, 149));
        jPanel2.setPreferredSize(new java.awt.Dimension(1160, 100));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        jPanel3.setPreferredSize(new java.awt.Dimension(411, 56));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro del Curso");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        jPanel4.setPreferredSize(new java.awt.Dimension(411, 56));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Configuración de notas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(314, 314, 314)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap())
        );

        LblPeriodoActual.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblPeriodoActual.setForeground(new java.awt.Color(255, 255, 255));
        LblPeriodoActual.setText("-");
        LblPeriodoActual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periodo Actual:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione el Curso:");

        CmbCurso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CmbCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12))); // NOI18N
        CmbCurso.setPreferredSize(new java.awt.Dimension(180, 50));
        CmbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCursoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seleccione el Ciclo:");

        cmbCiclo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbCiclo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciclo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Light", 0, 12))); // NOI18N
        cmbCiclo.setPreferredSize(new java.awt.Dimension(180, 50));
        cmbCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCicloActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("La Sección del Curso es:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cursose.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jLabel8.setMinimumSize(new java.awt.Dimension(72, 46));
        jLabel8.setName(""); // NOI18N
        jLabel8.setNextFocusableComponent(PnlRegCurso);
        jLabel8.setPreferredSize(new java.awt.Dimension(250, 290));

        jLabel9.setFont(new java.awt.Font("Dubai Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Determine el nombre, tipo y porcentaje de las notas del curso respectivo:");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nota 1:");

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nota 2:");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nota 3:");

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nota 4:");

        txtNota1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNota1.setPreferredSize(new java.awt.Dimension(190, 30));
        txtNota1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota1KeyTyped(evt);
            }
        });

        txtNota2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNota2.setPreferredSize(new java.awt.Dimension(190, 30));
        txtNota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota2KeyTyped(evt);
            }
        });

        txtNota3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNota3.setPreferredSize(new java.awt.Dimension(190, 30));
        txtNota3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota3KeyTyped(evt);
            }
        });

        txtNota4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNota4.setPreferredSize(new java.awt.Dimension(190, 30));
        txtNota4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNota4KeyTyped(evt);
            }
        });

        Lbltipo1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        Lbltipo1.setForeground(new java.awt.Color(255, 255, 255));
        Lbltipo1.setText("Participación");

        sp1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        sp1.setName(""); // NOI18N
        sp1.setPreferredSize(new java.awt.Dimension(50, 30));

        sp2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        sp2.setPreferredSize(new java.awt.Dimension(50, 30));

        sp3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        sp3.setPreferredSize(new java.awt.Dimension(50, 30));

        sp4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));
        sp4.setPreferredSize(new java.awt.Dimension(50, 30));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("%");

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("%");

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("%");

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("%");

        btnContinuar.setBackground(new java.awt.Color(181, 23, 23));
        btnContinuar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnContinuar.setPreferredSize(new java.awt.Dimension(190, 40));
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        LblSeccion.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        LblSeccion.setForeground(new java.awt.Color(255, 255, 255));
        LblSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblSeccion.setText("-");
        LblSeccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        RBtnUnica1.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup1.add(RBtnUnica1);
        RBtnUnica1.setForeground(new java.awt.Color(0, 0, 0));
        RBtnUnica1.setSelected(true);
        RBtnUnica1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnUnica1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnUnica1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnUnica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnUnica1ActionPerformed(evt);
            }
        });

        RBtnProm1.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup1.add(RBtnProm1);
        RBtnProm1.setForeground(new java.awt.Color(0, 0, 0));
        RBtnProm1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnProm1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnProm1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnProm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnProm1ActionPerformed(evt);
            }
        });

        RBtnPart1.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup1.add(RBtnPart1);
        RBtnPart1.setForeground(new java.awt.Color(0, 0, 0));
        RBtnPart1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnPart1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnPart1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnPart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnPart1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Porcentaje");

        Lbltipo2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        Lbltipo2.setForeground(new java.awt.Color(255, 255, 255));
        Lbltipo2.setText("Promedio");

        Lbltipo3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        Lbltipo3.setForeground(new java.awt.Color(255, 255, 255));
        Lbltipo3.setText("Unica");

        RBtnUnica2.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup2.add(RBtnUnica2);
        RBtnUnica2.setForeground(new java.awt.Color(0, 0, 0));
        RBtnUnica2.setSelected(true);
        RBtnUnica2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnUnica2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnUnica2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnUnica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnUnica2ActionPerformed(evt);
            }
        });

        RBtnPart2.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup2.add(RBtnPart2);
        RBtnPart2.setForeground(new java.awt.Color(0, 0, 0));
        RBtnPart2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnPart2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnPart2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnPart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnPart2ActionPerformed(evt);
            }
        });

        RBtnProm2.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup2.add(RBtnProm2);
        RBtnProm2.setForeground(new java.awt.Color(0, 0, 0));
        RBtnProm2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnProm2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnProm2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnProm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnProm2ActionPerformed(evt);
            }
        });

        RBtnUnica3.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup3.add(RBtnUnica3);
        RBtnUnica3.setForeground(new java.awt.Color(0, 0, 0));
        RBtnUnica3.setSelected(true);
        RBtnUnica3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnUnica3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnUnica3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnUnica3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnUnica3ActionPerformed(evt);
            }
        });

        RBtnPart3.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup3.add(RBtnPart3);
        RBtnPart3.setForeground(new java.awt.Color(0, 0, 0));
        RBtnPart3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnPart3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnPart3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnPart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnPart3ActionPerformed(evt);
            }
        });

        RBtnProm3.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup3.add(RBtnProm3);
        RBtnProm3.setForeground(new java.awt.Color(0, 0, 0));
        RBtnProm3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnProm3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnProm3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnProm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnProm3ActionPerformed(evt);
            }
        });

        RBtnUnica4.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup4.add(RBtnUnica4);
        RBtnUnica4.setForeground(new java.awt.Color(0, 0, 0));
        RBtnUnica4.setSelected(true);
        RBtnUnica4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnUnica4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnUnica4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnUnica4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnUnica4ActionPerformed(evt);
            }
        });

        RBtnPart4.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup4.add(RBtnPart4);
        RBtnPart4.setForeground(new java.awt.Color(0, 0, 0));
        RBtnPart4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnPart4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnPart4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnPart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnPart4ActionPerformed(evt);
            }
        });

        RBtnProm4.setBackground(new java.awt.Color(255, 255, 255));
        BtnGroup4.add(RBtnProm4);
        RBtnProm4.setForeground(new java.awt.Color(0, 0, 0));
        RBtnProm4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        RBtnProm4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RBtnProm4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        RBtnProm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtnProm4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlRegCursoLayout = new javax.swing.GroupLayout(PnlRegCurso);
        PnlRegCurso.setLayout(PnlRegCursoLayout);
        PnlRegCursoLayout.setHorizontalGroup(
            PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1136, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblPeriodoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(CmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(LblSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9))
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(Lbltipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Lbltipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Lbltipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel19))
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(15, 15, 15)
                        .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(RBtnUnica1)
                        .addGap(29, 29, 29)
                        .addComponent(RBtnPart1)
                        .addGap(39, 39, 39)
                        .addComponent(RBtnProm1)
                        .addGap(34, 34, 34)
                        .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(15, 15, 15)
                        .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(RBtnUnica2)
                        .addGap(29, 29, 29)
                        .addComponent(RBtnPart2)
                        .addGap(39, 39, 39)
                        .addComponent(RBtnProm2)
                        .addGap(34, 34, 34)
                        .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(15, 15, 15)
                        .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(RBtnUnica3)
                        .addGap(29, 29, 29)
                        .addComponent(RBtnPart3)
                        .addGap(39, 39, 39)
                        .addComponent(RBtnProm3)
                        .addGap(34, 34, 34)
                        .addComponent(sp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(15, 15, 15)
                        .addComponent(txtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(RBtnUnica4)
                        .addGap(29, 29, 29)
                        .addComponent(RBtnPart4)
                        .addGap(39, 39, 39)
                        .addComponent(RBtnProm4)
                        .addGap(34, 34, 34)
                        .addComponent(sp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PnlRegCursoLayout.setVerticalGroup(
            PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addComponent(LblPeriodoActual)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addGap(9, 9, 9)
                        .addComponent(cmbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(CmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(LblSeccion))
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlRegCursoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbltipo3)
                                    .addComponent(Lbltipo1)
                                    .addComponent(Lbltipo2))))
                        .addGap(1, 1, 1)
                        .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(RBtnUnica1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(RBtnPart1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(RBtnProm1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel15)))
                        .addGap(20, 20, 20)
                        .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11))
                            .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnUnica2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnPart2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnProm2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel16)))
                        .addGap(28, 28, 28)
                        .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12))
                            .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnUnica3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnPart3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnProm3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(sp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel17)))
                        .addGap(29, 29, 29)
                        .addGroup(PnlRegCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13))
                            .addComponent(txtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnUnica4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnPart4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(RBtnProm4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlRegCursoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel18)))
                        .addGap(77, 77, 77)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlRegCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlRegCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        int lleno, llenofinal = 0, porct;

        lleno = llenouno(txtNota1);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(txtNota2);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(txtNota3);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(txtNota4);
        llenofinal = llenofinal + lleno;

        if (llenofinal == 4) {
            LlenarNotasPorc(listaI);
            LlenarNotasN(listaS);
            if (!sonElementosIguales(listaS)) {
                int val1 = (int) sp1.getValue();
                int val2 = (int) sp2.getValue();
                int val3 = (int) sp3.getValue();
                int val4 = (int) sp4.getValue();

                porct = val1 + val2 + val3 + val4;

                if (porct == 100) {
                    if (porcero() != 0) {

                        Secca.setPeriodoSeccion(LblPeriodoActual.getText());
                        Secca.setNombreSeccion((String) CmbCurso.getSelectedItem());
                        Secca.setCicloSeccion((int) cmbCiclo.getSelectedItem());
                        Secca.setSeccionID(Integer.parseInt(LblSeccion.getText()));
                        Secca.setEstadoSeccion("Abierto");
                        Secca.setNotasNombres(listaS);
                        Secca.setNotasPorcentajes(listaI);

                        cmbCiclo.setSelectedIndex(0);
                        CmbCurso.setSelectedIndex(0);

                        //limpiar JTextField
                        Limpiar(txtNota1);
                        Limpiar(txtNota2);
                        Limpiar(txtNota3);
                        Limpiar(txtNota4);
                        //Limpiar Spinner's
                        sp1.setValue(0);
                        sp2.setValue(0);
                        sp3.setValue(0);
                        sp4.setValue(0);

                        PanelRegistroHorario pRH = new PanelRegistroHorario();
                        mostrarTipo(pRH);
                    } else {
                        JOptionPane.showMessageDialog(null, "Uno de los porcentajes tiene valor 0%");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "La suma de los porcentajes no es igual al 100%");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Los nombres de las notas no pueden ser iguales");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Aun no se han completado todos los campos");
        }

    }//GEN-LAST:event_btnContinuarActionPerformed

    private void CmbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCursoActionPerformed

    }//GEN-LAST:event_CmbCursoActionPerformed

    private void txtNota1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota1KeyTyped
        if (txtNota1.getText().length() > 19) {
            evt.consume();
        }

        char c = evt.getKeyChar();

        if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota1KeyTyped

    private void txtNota2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota2KeyTyped
        if (txtNota1.getText().length() > 19) {
            evt.consume();
        }

        char c = evt.getKeyChar();

        if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota2KeyTyped

    private void txtNota3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota3KeyTyped
        if (txtNota1.getText().length() > 19) {
            evt.consume();
        }

        char c = evt.getKeyChar();

        if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota3KeyTyped

    private void txtNota4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNota4KeyTyped
        if (txtNota1.getText().length() > 19) {
            evt.consume();
        }

        char c = evt.getKeyChar();

        if (!Character.isLetterOrDigit(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNota4KeyTyped

    private void cmbCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCicloActionPerformed
        // TODO add your handling code here:
        if (valCiclo == 1) {
            CmbCurso.removeAllItems();
            S.setCicloSeccion((int) cmbCiclo.getSelectedItem());
            DAOs.cargar(S, CmbCurso);
        }
    }//GEN-LAST:event_cmbCicloActionPerformed

    private void RBtnUnica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnUnica1ActionPerformed
        Secca.setNotasTip(0, "Unica");
    }//GEN-LAST:event_RBtnUnica1ActionPerformed

    private void RBtnPart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnPart1ActionPerformed
        Secca.setNotasTip(0, "Participacion");
    }//GEN-LAST:event_RBtnPart1ActionPerformed

    private void RBtnProm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnProm1ActionPerformed
        Secca.setNotasTip(0, "Promedio");
    }//GEN-LAST:event_RBtnProm1ActionPerformed

    private void RBtnUnica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnUnica2ActionPerformed
        Secca.setNotasTip(1, "Unica");
    }//GEN-LAST:event_RBtnUnica2ActionPerformed

    private void RBtnPart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnPart2ActionPerformed
        Secca.setNotasTip(1, "Participacion");
    }//GEN-LAST:event_RBtnPart2ActionPerformed

    private void RBtnProm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnProm2ActionPerformed
        Secca.setNotasTip(1, "Promedio");
    }//GEN-LAST:event_RBtnProm2ActionPerformed

    private void RBtnUnica3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnUnica3ActionPerformed
        Secca.setNotasTip(2, "Unica");
    }//GEN-LAST:event_RBtnUnica3ActionPerformed

    private void RBtnPart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnPart3ActionPerformed
        Secca.setNotasTip(2, "Participacion");
    }//GEN-LAST:event_RBtnPart3ActionPerformed

    private void RBtnProm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnProm3ActionPerformed
        Secca.setNotasTip(2, "Promedio");
    }//GEN-LAST:event_RBtnProm3ActionPerformed

    private void RBtnUnica4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnUnica4ActionPerformed
        Secca.setNotasTip(3, "Unica");
    }//GEN-LAST:event_RBtnUnica4ActionPerformed

    private void RBtnPart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnPart4ActionPerformed
        Secca.setNotasTip(3, "Participacion");
    }//GEN-LAST:event_RBtnPart4ActionPerformed

    private void RBtnProm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtnProm4ActionPerformed
        Secca.setNotasTip(3, "Promedio");
    }//GEN-LAST:event_RBtnProm4ActionPerformed
    private void GenerarSeccion() {
        int seccionAleat;
        int sA;
        int auxComp, sAaux;
        String sFormateado;
        do {
            int numeroAleatorio = (int) (Math.random() * 9000) + 1000;
            S.setSeccionID(numeroAleatorio);
            sFormateado = Integer.toString(numeroAleatorio);
            auxComp = DAOs.comparar(S);
        } while (auxComp == 1 || sFormateado.length() > 5);

    }

    private void LlenarNotasPorc(int Lista[]) {
        Lista[0] = (int) sp1.getValue();
        Lista[1] = (int) sp2.getValue();
        Lista[2] = (int) sp3.getValue();
        Lista[3] = (int) sp4.getValue();
    }

    private void LlenarNotasN(String Lista[]) {
        Lista[0] = txtNota1.getText();
        Lista[1] = txtNota2.getText();
        Lista[2] = txtNota3.getText();
        Lista[3] = txtNota4.getText();
    }

    private int porcero() {
        int valor;
        valor = (int) sp1.getValue();
        if (valor != 0) {
            valor = (int) sp2.getValue();
            if (valor != 0) {
                valor = (int) sp3.getValue();
                if (valor != 0) {
                    valor = (int) sp4.getValue();
                    if (valor != 0) {
                        valor = 1;
                    }
                }
            }
        }

        return valor;
    }

    public int llenouno(JTextField TextoCanal) {
        String val;
        val = TextoCanal.getText();
        int b;
        if (val.isEmpty()) {
            b = 0;
        } else {
            b = 1;
        }
        return b;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroup1;
    private javax.swing.ButtonGroup BtnGroup2;
    private javax.swing.ButtonGroup BtnGroup3;
    private javax.swing.ButtonGroup BtnGroup4;
    private javax.swing.JComboBox<String> CmbCurso;
    private javax.swing.JLabel LblPeriodoActual;
    private javax.swing.JLabel LblSeccion;
    private javax.swing.JLabel Lbltipo1;
    private javax.swing.JLabel Lbltipo2;
    private javax.swing.JLabel Lbltipo3;
    private javax.swing.JPanel PnlRegCurso;
    private javax.swing.JRadioButton RBtnPart1;
    private javax.swing.JRadioButton RBtnPart2;
    private javax.swing.JRadioButton RBtnPart3;
    private javax.swing.JRadioButton RBtnPart4;
    private javax.swing.JRadioButton RBtnProm1;
    private javax.swing.JRadioButton RBtnProm2;
    private javax.swing.JRadioButton RBtnProm3;
    private javax.swing.JRadioButton RBtnProm4;
    private javax.swing.JRadioButton RBtnUnica1;
    private javax.swing.JRadioButton RBtnUnica2;
    private javax.swing.JRadioButton RBtnUnica3;
    private javax.swing.JRadioButton RBtnUnica4;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cmbCiclo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner sp1;
    private javax.swing.JSpinner sp2;
    private javax.swing.JSpinner sp3;
    private javax.swing.JSpinner sp4;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    // End of variables declaration//GEN-END:variables
}
