/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsGenerales;

import Informacion.Docente;
import Interfaces.Carreras;
import Interfaces.DAODocenteImplement;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class PanelRegistroDocente extends javax.swing.JPanel {

    DAODocenteImplement DAOd = new DAODocenteImplement();
    Carreras C = new Carreras();
    Docente docente = new Docente();
    int valCarrera = 0;

    /**
     * Creates new form PanelRegistroDocente
     */
    public PanelRegistroDocente() {
        initComponents();
        C.RellenarCmbcarrera(CmbBoxProfesiones);
    }

    public void Limpiar(JTextField texto) {
        texto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlRegDocente = new javax.swing.JPanel();
        BtnRegistrar = new javax.swing.JButton();
        TxtNombreDocente = new javax.swing.JTextField();
        TxtApellidoPDocente = new javax.swing.JTextField();
        TxtApellidoMDocente = new javax.swing.JTextField();
        TxtNroDocDocente = new javax.swing.JTextField();
        TxtEdadDocente = new javax.swing.JTextField();
        TxtTelefonoDocente = new javax.swing.JTextField();
        TxtCorreoPDocente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CmbBoxProfesiones = new javax.swing.JComboBox<>();
        SliderContrato = new javax.swing.JSlider();
        CheckBoxMaestria = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        PnlRegDocente.setBackground(new java.awt.Color(0, 153, 204));
        PnlRegDocente.setForeground(new java.awt.Color(255, 255, 255));

        BtnRegistrar.setBackground(new java.awt.Color(0, 102, 204));
        BtnRegistrar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hacerotros32x32.png"))); // NOI18N
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 5, 1, 1, new java.awt.Color(0, 0, 0)));
        BtnRegistrar.setBorderPainted(false);
        BtnRegistrar.setIconTextGap(15);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        TxtNombreDocente.setForeground(new java.awt.Color(0, 0, 0));
        TxtNombreDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        TxtNombreDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreDocenteKeyTyped(evt);
            }
        });

        TxtApellidoPDocente.setForeground(new java.awt.Color(0, 0, 0));
        TxtApellidoPDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido Paterno:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        TxtApellidoPDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidoPDocenteKeyTyped(evt);
            }
        });

        TxtApellidoMDocente.setForeground(new java.awt.Color(0, 0, 0));
        TxtApellidoMDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido Materno:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        TxtApellidoMDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtApellidoMDocenteKeyTyped(evt);
            }
        });

        TxtNroDocDocente.setForeground(new java.awt.Color(0, 0, 0));
        TxtNroDocDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nro de Documento:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        TxtNroDocDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNroDocDocenteKeyTyped(evt);
            }
        });

        TxtEdadDocente.setForeground(new java.awt.Color(0, 0, 0));
        TxtEdadDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        TxtEdadDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEdadDocenteKeyTyped(evt);
            }
        });

        TxtTelefonoDocente.setForeground(new java.awt.Color(0, 0, 0));
        TxtTelefonoDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        TxtTelefonoDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefonoDocenteKeyTyped(evt);
            }
        });

        TxtCorreoPDocente.setForeground(new java.awt.Color(0, 0, 0));
        TxtCorreoPDocente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo Personal:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ebrima", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        TxtCorreoPDocente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCorreoPDocenteKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATOS DEL DOCENTE");

        CmbBoxProfesiones.setBackground(new java.awt.Color(255, 255, 255));
        CmbBoxProfesiones.setForeground(new java.awt.Color(0, 0, 0));
        CmbBoxProfesiones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profesión:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        CmbBoxProfesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbBoxProfesionesActionPerformed(evt);
            }
        });

        SliderContrato.setBackground(new java.awt.Color(255, 255, 255));
        SliderContrato.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        SliderContrato.setForeground(new java.awt.Color(0, 0, 0));
        SliderContrato.setMajorTickSpacing(30);
        SliderContrato.setMaximum(180);
        SliderContrato.setMinimum(90);
        SliderContrato.setMinorTickSpacing(30);
        SliderContrato.setPaintLabels(true);
        SliderContrato.setPaintTicks(true);
        SliderContrato.setSnapToTicks(true);
        SliderContrato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Duración del contrato:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        CheckBoxMaestria.setBackground(new java.awt.Color(255, 255, 255));
        CheckBoxMaestria.setForeground(new java.awt.Color(0, 0, 0));
        CheckBoxMaestria.setText("Maestría");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/docentedos.png"))); // NOI18N

        javax.swing.GroupLayout PnlRegDocenteLayout = new javax.swing.GroupLayout(PnlRegDocente);
        PnlRegDocente.setLayout(PnlRegDocenteLayout);
        PnlRegDocenteLayout.setHorizontalGroup(
            PnlRegDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegDocenteLayout.createSequentialGroup()
                .addGroup(PnlRegDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlRegDocenteLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(PnlRegDocenteLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CmbBoxProfesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(TxtNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlRegDocenteLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(TxtApellidoPDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlRegDocenteLayout.createSequentialGroup()
                        .addGroup(PnlRegDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnlRegDocenteLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addGroup(PnlRegDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxMaestria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtApellidoMDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtEdadDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNroDocDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTelefonoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCorreoPDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SliderContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        PnlRegDocenteLayout.setVerticalGroup(
            PnlRegDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRegDocenteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(PnlRegDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CmbBoxProfesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(TxtApellidoPDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(PnlRegDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlRegDocenteLayout.createSequentialGroup()
                        .addComponent(TxtApellidoMDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(TxtEdadDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(TxtNroDocDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(TxtTelefonoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(TxtCorreoPDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SliderContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(PnlRegDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBoxMaestria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlRegDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlRegDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        int slider;
        int lleno, llenofinal = 0, edadaux;

        lleno = llenouno(TxtNroDocDocente);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(TxtNombreDocente);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(TxtEdadDocente);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(TxtApellidoPDocente);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(TxtApellidoMDocente);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(TxtCorreoPDocente);
        llenofinal = llenofinal + lleno;
        lleno = llenouno(TxtTelefonoDocente);
        llenofinal = llenofinal + lleno;
        if (llenofinal == 7) {
            edadaux = Integer.parseInt(TxtEdadDocente.getText());
            if (edadaux <= 80 && edadaux >= 25) {
                docente.setNombre(TxtNombreDocente.getText());
                docente.setApeP(TxtApellidoPDocente.getText());
                docente.setEdad(edadaux);
                docente.setApeM(TxtApellidoMDocente.getText());
                docente.setDNI(TxtNroDocDocente.getText());
                docente.setCorreopersonal(TxtCorreoPDocente.getText());
                docente.setTelefono(TxtTelefonoDocente.getText());
                docente.setTitulo((String) CmbBoxProfesiones.getSelectedItem());

                docente.setEstado("Activo");
                docente.setRol("Docente");
                if (CheckBoxMaestria.isSelected()) {
                    docente.setEspecializacion("Maestría");
                } else {
                    docente.setEspecializacion("No");
                }
                slider = SliderContrato.getValue();
                docente.setContrato(Integer.toString(slider) + " días");
                if (docente.getTelefono().length() == 9) {
                    if (docente.getDNI().length() == 8) {
                        docente.setCodigoUsu(GenerarCodigo(docente.getDNI(), docente.getEdad()));
                        docente.setClave(GenerarClave(docente.getDNI(), docente.getEdad()));
                        DAOd.registrar(docente);
                        CmbBoxProfesiones.setSelectedIndex(0);
                        Limpiar(TxtNombreDocente);
                        Limpiar(TxtEdadDocente);
                        Limpiar(TxtApellidoPDocente);
                        Limpiar(TxtApellidoMDocente);
                        Limpiar(TxtCorreoPDocente);
                        Limpiar(TxtTelefonoDocente);
                        Limpiar(TxtNroDocDocente);
                    } else {
                        JOptionPane.showMessageDialog(null, "El DNI debe tener solo 8 digitos");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El telefono debe tener solo 9 digitos");

                }
            } else {
                JOptionPane.showMessageDialog(null, "La edad del docente debe ser entre 25 a 80 años");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Aun no se han completado todos los campos");
        }


    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void CmbBoxProfesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbBoxProfesionesActionPerformed
        /*if (valCarrera == 1) {
            CmbBoxCiclos.removeAllItems();
            alumno.setCarrera((String) CmbBoxProfesiones.getSelectedItem());
            // System.out.println(alumno.getCarrera());
            C.RellenarCiclo(CmbBoxCiclos, alumno.getCarrera());
        }*/

    }//GEN-LAST:event_CmbBoxProfesionesActionPerformed

    private void TxtNroDocDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNroDocDocenteKeyTyped
        if (TxtNroDocDocente.getText().length() > 7) {      // 1.si se pasa de 6 valores
            evt.consume();                           //   ya no dejara escirbir
        }
        char caracter = evt.getKeyChar();            // 2.almacenando una tecla presiona

        if ((caracter < '0' || caracter > '9')
                && (caracter != KeyEvent.VK_BACK_SPACE)) {// 3. si se cumple 
            evt.consume();                                // no dejara esribir  
        }
    }//GEN-LAST:event_TxtNroDocDocenteKeyTyped

    private void TxtNombreDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreDocenteKeyTyped
        if (TxtNombreDocente.getText().length() > 49) {
            evt.consume();
        }
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtNombreDocenteKeyTyped

    private void TxtApellidoPDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoPDocenteKeyTyped
        if (TxtApellidoPDocente.getText().length() > 49) {
            evt.consume();
        }
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtApellidoPDocenteKeyTyped

    private void TxtApellidoMDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtApellidoMDocenteKeyTyped
        if (TxtApellidoMDocente.getText().length() > 49) {
            evt.consume();
        }
        char c = evt.getKeyChar();

        if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtApellidoMDocenteKeyTyped

    private void TxtEdadDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEdadDocenteKeyTyped
        char caracter = evt.getKeyChar();            // 2.almacenando una tecla presiona

        if ((caracter < '0' || caracter > '9')
                && (caracter != KeyEvent.VK_BACK_SPACE)) {// 3. si se cumple 
            evt.consume();                                // no dejara esribir  
        }
    }//GEN-LAST:event_TxtEdadDocenteKeyTyped

    private void TxtTelefonoDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoDocenteKeyTyped
        if (TxtTelefonoDocente.getText().length() > 8) {      // 1.si se pasa de 6 valores
            evt.consume();                           //   ya no dejara escirbir
        }
        char caracter = evt.getKeyChar();            // 2.almacenando una tecla presiona

        if ((caracter < '0' || caracter > '9')
                && (caracter != KeyEvent.VK_BACK_SPACE)) {// 3. si se cumple 
            evt.consume();                                // no dejara esribir  
        }
    }//GEN-LAST:event_TxtTelefonoDocenteKeyTyped

    private void TxtCorreoPDocenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreoPDocenteKeyTyped
        char c = evt.getKeyChar();
        if (TxtCorreoPDocente.getText().length() > 29) {
            evt.consume();
        }
        if (!Character.isLetterOrDigit(c) && c != '@' && c != '.' && c != '_' && c != '-' && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtCorreoPDocenteKeyTyped
    public String GenerarCodigo(String DNI, int Edad) {
        // NuevoCodigo = Integer.toString(NCaux);
        String NuevoCodigo;
        int auxComp;
        int DNIaux, NCaux, Aleatorio;
        int val1, val2;

        if (DNI == null || Edad == 0) {
            NuevoCodigo = null;
        } else {
            DNIaux = Integer.parseInt(DNI);
            val1 = DNIaux;
            val2 = Edad;
            do {
                DNIaux = val1;
                Edad = val2;
                Aleatorio = (int) (Math.random() * (9000 - 1000 + 1)) + 1000;
                NCaux = (DNIaux + Edad) - Aleatorio;
                //System.out.println("Antes: "+NCaux);
                NCaux = NCaux % 1000000;
                //System.out.println("Despues: "+NCaux);
                String numeroFormateado = String.format("%06d", NCaux);
                // System.out.println(numeroFormateado);
                NuevoCodigo = "D" + numeroFormateado;
                docente.setCodigoUsu(NuevoCodigo);
                auxComp = DAOd.comparar(docente);
            } while (auxComp == 1 || NuevoCodigo.length() > 7);

        }
        return NuevoCodigo;
    }

    public String GenerarClave(String DNI, int Edad) {
        String NuevaClave;
        int DNIaux, NCaux, Aleatorio;
        DNIaux = Integer.parseInt(DNI);
        Aleatorio = (int) (Math.random() * (9000 - 1000 + 1)) + 1000;
        NCaux = (DNIaux + Edad) - (int) Aleatorio;
        NuevaClave = Integer.toString(NCaux);
        return NuevaClave;
    }

    public int llenouno(JTextField TextoCanal) {
        String val;
        val = TextoCanal.getText();
        int b;
        if (val.isEmpty()) {
            b = 0;
        } else {
            b = 1;
        }
        return b;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JCheckBox CheckBoxMaestria;
    private javax.swing.JComboBox<String> CmbBoxProfesiones;
    private javax.swing.JPanel PnlRegDocente;
    private javax.swing.JSlider SliderContrato;
    private javax.swing.JTextField TxtApellidoMDocente;
    private javax.swing.JTextField TxtApellidoPDocente;
    private javax.swing.JTextField TxtCorreoPDocente;
    private javax.swing.JTextField TxtEdadDocente;
    private javax.swing.JTextField TxtNombreDocente;
    private javax.swing.JTextField TxtNroDocDocente;
    private javax.swing.JTextField TxtTelefonoDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
