/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsAlumno;

import Informacion.Matriculas;
import Informacion.ValoresEstaticos;
import Interfaces.DAOMatriculasImplement;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Hashtable;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author medal
 */
public class AgregarCurso extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCurso
     */
    Matriculas VEMS = ValoresEstaticos.VEM;
    DAOMatriculasImplement DAOM = new DAOMatriculasImplement();
    Matriculas M = new Matriculas();
    Hashtable<Integer, String> tempHT = new Hashtable<>();
    String h1, h2 = "";
    int b = 0;

    public AgregarCurso() {
        initComponents();
        lblCurso.setText(VEMS.getNombreCurso());
        lblCiclo.setText(Integer.toString(VEMS.getCicloid()));
        M.setNroseccion(VEMS.getNroseccion());
        M.setAlumnoid(VEMS.getAlumnoid());
        System.out.println("AlSP: " + M.getAlumnoid());
        M.setCicloid(VEMS.getCicloid());
        M.setPeriodoid(VEMS.getPeriodoid());
        M.setCursoID(VEMS.getCursoID());
        DAOM.CargarSeccionesDisponibles(M, tblAgregarCurso);
        VEMS.getMiHashtable().clear();
        tempHT = VEMS.getMiHashtable();
        String mensaje = "";
        for (int i = 0; i < VEMS.getHorarioF().length; i++) {
            if (VEMS.getHorarioEsp(i) != null) {
                tempHT.put(i, VEMS.getHorarioEsp(i));
            }

            mensaje += "|" + VEMS.getHorarioEsp(i);
        }
        System.out.println("Horarios:" + mensaje);
    }

    class Render extends DefaultTableCellRenderer {

        private final JButton button = new JButton("Seleccionar");

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            button.setBackground(Color.GREEN);
            button.setForeground(Color.WHITE);
            return button;
        }
    }

    class ButtonEditor extends DefaultCellEditor {

        private final JButton button;
        private String label;
        private boolean isPushed;

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);
            button.setBackground(Color.GREEN);
            button.setForeground(Color.WHITE);
            button.addActionListener(e -> fireEditingStopped());
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            label = "Seleccionar";
            button.setText(label);
            isPushed = true;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed) {
                b = 0;
                for (int i = 0; i < VEMS.getHorarioF().length; i++) {
                    if (tempHT.containsKey(i)) {
                        String contenido = tempHT.get(i);

                        if (contenido.equals(h1) || contenido.equals(h2)) {
                            JOptionPane.showMessageDialog(null, "Existe cruce de Horario si escoges este horario\nEscoge otro horario");
                            b = 1;
                        }
                    }
                }
                if (b == 0) {
                    DAOM.AgregarSeccionesMatriculadas(M);
                    PanelCursoMatricular pCM = new PanelCursoMatricular();
                    mostrarTipo(pCM);
                }
            }
            isPushed = false;
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }
    }

    public void mostrarTipo(JPanel j) {

        j.setSize(1160, 537);
        j.setLocation(0, 0);

        PnlSeccionesDisp.removeAll();
        PnlSeccionesDisp.add(j, BorderLayout.CENTER);
        PnlSeccionesDisp.revalidate();
        PnlSeccionesDisp.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlSeccionesDisp = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCiclo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgregarCurso = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        PnlSeccionesDisp.setBackground(new java.awt.Color(0, 102, 51));
        PnlSeccionesDisp.setPreferredSize(new java.awt.Dimension(1160, 537));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(660, 400));

        jPanel3.setBackground(new java.awt.Color(186, 46, 46));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Secciones Disponibles");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Curso:");

        lblCurso.setText("-");
        lblCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        lblCurso.setPreferredSize(new java.awt.Dimension(150, 50));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ciclo:");

        lblCiclo.setText("-");
        lblCiclo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciclo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        lblCiclo.setPreferredSize(new java.awt.Dimension(150, 50));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Selecciona el turno y la sección en el horario de tu preferencia. Elige la opción \"Seleccionar\" en la fila de la sección deseada. Si el horario de la sección se cruza");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("con otros que hayas elegido previamente, no podrás elegirla.");

        tblAgregarCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        tblAgregarCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Seccion", "Docente", "Horario", "Acción"
            }
        ));
        tblAgregarCurso.setGridColor(new java.awt.Color(153, 153, 153));
        tblAgregarCurso.setInheritsPopupMenu(true);
        tblAgregarCurso.setRowHeight(25);
        tblAgregarCurso.setRowSelectionAllowed(false);
        tblAgregarCurso.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblAgregarCurso.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAgregarCurso.setShowGrid(true);
        tblAgregarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAgregarCursoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblAgregarCursoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblAgregarCurso);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sombmat.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(182, 182, 46));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Regresar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lblCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lblCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlSeccionesDispLayout = new javax.swing.GroupLayout(PnlSeccionesDisp);
        PnlSeccionesDisp.setLayout(PnlSeccionesDispLayout);
        PnlSeccionesDispLayout.setHorizontalGroup(
            PnlSeccionesDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSeccionesDispLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PnlSeccionesDispLayout.setVerticalGroup(
            PnlSeccionesDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlSeccionesDispLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlSeccionesDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlSeccionesDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblAgregarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgregarCursoMouseClicked
        // TODO add your handling code here:
//        tblAgregarCurso.getColumnModel().getColumn(tblAgregarCurso.getColumnCount() - 1).setCellRenderer(new Render ());
//        tblAgregarCurso.getColumnModel().getColumn(tblAgregarCurso.getColumnCount() - 1).setCellEditor(new ButtonEditor(new JCheckBox()));
    }//GEN-LAST:event_tblAgregarCursoMouseClicked

    private void tblAgregarCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAgregarCursoMousePressed

        int fila = tblAgregarCurso.getSelectedRow();

        if (fila != -1) {
            String Seccion = tblAgregarCurso.getValueAt(fila, tblAgregarCurso.getColumnModel().getColumnIndex("Seccion")).toString();
            String horarioconca = tblAgregarCurso.getValueAt(fila, tblAgregarCurso.getColumnModel().getColumnIndex("Horario")).toString();
            M.setNroseccion(Integer.parseInt(Seccion));
            if (horarioconca.contains(" y ")) {
                String[] partes = horarioconca.split(" y ");
                h1 = partes[0];
                h2 = partes[1];
            } else {
                h1 = horarioconca;
            }

        }

        tblAgregarCurso.getColumnModel().getColumn(tblAgregarCurso.getColumnCount() - 1).setCellRenderer(new Render());
        tblAgregarCurso.getColumnModel().getColumn(tblAgregarCurso.getColumnCount() - 1).setCellEditor(new ButtonEditor(new JCheckBox()));
    }//GEN-LAST:event_tblAgregarCursoMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PanelCursoMatricular pCM = new PanelCursoMatricular();
        mostrarTipo(pCM);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlSeccionesDisp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCiclo;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JTable tblAgregarCurso;
    // End of variables declaration//GEN-END:variables
}
