/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsAlumno;

import Informacion.Alumno;
import Informacion.Usuario;
import Informacion.ValoresEstaticos;
import Interfaces.DAOAlumnoImplement;
import java.awt.BorderLayout;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author medal
 */
public class PanelEmpezarmatricula extends javax.swing.JPanel {

    private int generatedPin;
    DAOAlumnoImplement DAlum = new DAOAlumnoImplement();
    Alumno EAlum = ValoresEstaticos.Alu;
    Alumno alumno = new Alumno();
    Usuario Usua = ValoresEstaticos.Usu;

    public PanelEmpezarmatricula() {
        initComponents();
        alumno.setID(Usua.getID());
        alumno.setCodigoUsu(Usua.getCodigoUsu());
        EAlum.setCodigoUsu(alumno.getCodigoUsu());
        EAlum.setID(alumno.getID());
        DAlum.validarPagoMatricula(alumno);
        generatedPin = generatePin(); //
        jLabelPin.setText(String.format("%04d", generatedPin));
    }

    public void mostrarTipo(JPanel j) {

        j.setSize(1160, 537);
        j.setLocation(0, 0);

        PnlPrincipal.removeAll();
        PnlPrincipal.add(j, BorderLayout.CENTER);
        PnlPrincipal.revalidate();
        PnlPrincipal.repaint();
    }

    private int generatePin() {
        Random random = new Random();
        return 1000 + random.nextInt(9000); // Generar un número aleatorio entre 1000 y 9999
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPin = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelPin = new javax.swing.JLabel();
        PnlEM = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1160, 537));

        PnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PnlPrincipal.setPreferredSize(new java.awt.Dimension(1160, 537));

        jPanel2.setBackground(new java.awt.Color(186, 46, 46));
        jPanel2.setPreferredSize(new java.awt.Dimension(222, 537));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoutp.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Matricúlate");

        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextPin.setColumns(1);
        jTextPin.setRows(1);
        jTextPin.setTabSize(1);
        jTextPin.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTextPin);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa el código:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PIN:");

        jLabelPin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelPin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPin.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel4))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabelPin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addComponent(jLabelPin)
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jButton1))
        );

        PnlEM.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout PnlEMLayout = new javax.swing.GroupLayout(PnlEM);
        PnlEM.setLayout(PnlEMLayout);
        PnlEMLayout.setHorizontalGroup(
            PnlEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        PnlEMLayout.setVerticalGroup(
            PnlEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PnlPrincipalLayout = new javax.swing.GroupLayout(PnlPrincipal);
        PnlPrincipal.setLayout(PnlPrincipalLayout);
        PnlPrincipalLayout.setHorizontalGroup(
            PnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PnlEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnlPrincipalLayout.setVerticalGroup(
            PnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PnlEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String enteredPin = jTextPin.getText();
        if (enteredPin.length() == 4) {
            int enteredPinInt = Integer.parseInt(enteredPin);
            if (enteredPinInt == generatedPin) {
                String[] resultados = DAlum.validarPagoMatricula(alumno);

                if (resultados != null) {
                    String estadoPago = resultados[1];
                    if ("Pendiente".equalsIgnoreCase(estadoPago)) {
                        PagarMatricula pMat = new PagarMatricula();
                        pMat.setVisible(true);
                        pMat.setLocationRelativeTo(null);
                    } else if ("Pagado".equalsIgnoreCase(estadoPago)) {
                        PanelCursoMatricular PCM = new PanelCursoMatricular();
                        mostrarTipo(PCM);
                    }
                }
                 generatedPin = generatePin();
                jLabelPin.setText(String.format("%04d", generatedPin));
            } else {
                // PIN incorrecto, mostrar mensaje de error y generar otro PIN
                generatedPin = generatePin();
                jLabelPin.setText(String.format("%04d", generatedPin));
                JOptionPane.showMessageDialog(this, "PIN incorrecto. Se ha generado un nuevo PIN.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un PIN de 4 dígitos.");
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlEM;
    private javax.swing.JPanel PnlPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextPin;
    // End of variables declaration//GEN-END:variables
}
