/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsAlumno;

import Informacion.Alumno;
import Informacion.EstadoPeriodos;
import Informacion.Matriculas;
import Informacion.Usuario;
import Informacion.ValoresEstaticos;
import Interfaces.DAOMatriculasImplement;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Hashtable;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author medal
 */
public class PanelCursoMatricular extends javax.swing.JPanel {

    Usuario Usua = ValoresEstaticos.Usu;
    Alumno AluS = ValoresEstaticos.Alu;
    EstadoPeriodos VEPST = ValoresEstaticos.VEPST;
    Matriculas VEMS = ValoresEstaticos.VEM;
    Matriculas M = new Matriculas();
    DAOMatriculasImplement DAOM = new DAOMatriculasImplement();
    int a = 0;

    public PanelCursoMatricular() {
        initComponents();
        LblNombreCompleto.setText(Usua.getNombrecompleto());
        LblCarrera.setText(AluS.getNombreCarrera());
        M.setAlumnoid(Usua.getID());
        M.setCicloid(AluS.getCiclo());
        M.setPeriodoid(VEPST.getIdp());
        DAOM.CargarCursosDisponibles(M, tblEscogerCurso);
        DAOM.CargarSeccionesMatriculadas(M, tblMatriculado);
    }

    class Render extends DefaultTableCellRenderer {

        private final JButton button;

        public Render(String buttonText, Color buttonColor) {
            this.button = new JButton(buttonText);
            this.button.setBackground(buttonColor);
            this.button.setForeground(Color.WHITE);
            System.out.println("Line: 61");
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            return button;

        }
    }

    class ButtonEditor extends DefaultCellEditor {

        private final JButton button;
        private String label;
        private boolean isPushed;

        public ButtonEditor(Color buttonColor, String label, JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setForeground(Color.WHITE);
            this.label = label;
            this.isPushed = true;

            button.addActionListener(e -> fireEditingStopped());

        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {

            button.setText(label);
            isPushed = true;
            return button;

        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed) {
                if (a == 0) {
                    VEMS.setAlumnoid(M.getAlumnoid());
                    System.out.println("AlPP2: " + VEMS.getAlumnoid());
                    VEMS.setCicloid(M.getCicloid());
                    VEMS.setPeriodoid(M.getPeriodoid());

                    AgregarCurso pSD = new AgregarCurso();
                    mostrarTipo(pSD);
                } else {

                    DAOM.EliminarSeccionesMatriculadas(M);
                    DAOM.CargarCursosDisponibles(M, tblEscogerCurso);
                    System.out.println("Se elimino");

                    stopCellEditing();
                    DAOM.CargarSeccionesMatriculadas(M, tblMatriculado);
                    ((AbstractTableModel) tblMatriculado.getModel()).fireTableDataChanged();

//      System.out.println("CargoSecciones");
                }
                System.out.println("Line: 116");
            }
            System.out.println(label);
            isPushed = false;
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();

        }
    }

    public void mostrarTipo(JPanel j) {

        j.setSize(1160, 537);
        j.setLocation(0, 0);

        pnlCursosMatricular.removeAll();
        pnlCursosMatricular.add(j, BorderLayout.CENTER);
        pnlCursosMatricular.revalidate();
        pnlCursosMatricular.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCursosMatricular = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEscogerCurso = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        LblNombreCompleto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LblCarrera = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatriculado = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        pnlCursosMatricular.setBackground(new java.awt.Color(0, 102, 51));
        pnlCursosMatricular.setPreferredSize(new java.awt.Dimension(1160, 537));

        jPanel2.setBackground(new java.awt.Color(186, 46, 46));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cursos a Matricular");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(465, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(410, 410, 410))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Aquí encontrarás la lista de cursos aptos para matricularte. ");

        tblEscogerCurso.setAutoCreateRowSorter(true);
        tblEscogerCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)));
        tblEscogerCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Curso", "Cantidad", "Acción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblEscogerCurso.setGridColor(new java.awt.Color(102, 102, 102));
        tblEscogerCurso.setName(""); // NOI18N
        tblEscogerCurso.setRowHeight(30);
        tblEscogerCurso.setShowGrid(true);
        tblEscogerCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEscogerCursoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblEscogerCursoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEscogerCurso);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre del Alumno:");

        LblNombreCompleto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNombreCompleto.setForeground(new java.awt.Color(255, 255, 255));
        LblNombreCompleto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre Completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        LblNombreCompleto.setPreferredSize(new java.awt.Dimension(250, 50));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Carrera:");

        LblCarrera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblCarrera.setForeground(new java.awt.Color(255, 255, 255));
        LblCarrera.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        LblCarrera.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setText("con tu plan de estudios.");

        jPanel3.setBackground(new java.awt.Color(72, 128, 63));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblMatriculado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        tblMatriculado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seccion", "Horario", "Docente", "Curso", "Accion"
            }
        ));
        tblMatriculado.setGridColor(new java.awt.Color(102, 102, 102));
        tblMatriculado.setRowHeight(30);
        tblMatriculado.setShowGrid(true);
        tblMatriculado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMatriculadoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblMatriculado);
        tblMatriculado.getAccessibleContext().setAccessibleParent(jPanel3);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tabla Cursos Matriculados");

        jLabel10.setText("Aquí encontrarás la lista de cursos de los cuales ya te has matriculado:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(156, 156, 156))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Elige primero los cursos de menor nivel para avanzar de acuerdo ");

        javax.swing.GroupLayout pnlCursosMatricularLayout = new javax.swing.GroupLayout(pnlCursosMatricular);
        pnlCursosMatricular.setLayout(pnlCursosMatricularLayout);
        pnlCursosMatricularLayout.setHorizontalGroup(
            pnlCursosMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursosMatricularLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCursosMatricularLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlCursosMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCursosMatricularLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5))
                    .addGroup(pnlCursosMatricularLayout.createSequentialGroup()
                        .addComponent(LblNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(LblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCursosMatricularLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlCursosMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCursosMatricularLayout.setVerticalGroup(
            pnlCursosMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursosMatricularLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(pnlCursosMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCursosMatricularLayout.createSequentialGroup()
                        .addGroup(pnlCursosMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addGroup(pnlCursosMatricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCursosMatricularLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCursosMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCursosMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblEscogerCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEscogerCursoMouseClicked

//        tblEscogerCurso.getColumnModel().getColumn(tblEscogerCurso.getColumnCount() - 1).setCellRenderer(new Render ());
//        tblEscogerCurso.getColumnModel().getColumn(tblEscogerCurso.getColumnCount() - 1).setCellEditor(new ButtonEditor(new JCheckBox()));

    }//GEN-LAST:event_tblEscogerCursoMouseClicked

    private void tblEscogerCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEscogerCursoMousePressed
        // TODO add your handling code here:

        int fila = tblEscogerCurso.getSelectedRow();

        if (fila != -1) {
            a = 0;
            String ID = tblEscogerCurso.getValueAt(fila, tblEscogerCurso.getColumnModel().getColumnIndex("Item")).toString();
            String Nombre = tblEscogerCurso.getValueAt(fila, tblEscogerCurso.getColumnModel().getColumnIndex("Curso")).toString();
            VEMS.setCursoID(Integer.parseInt(ID));
            VEMS.setNombreCurso(Nombre);
        }
        tblEscogerCurso.getColumnModel().getColumn(tblEscogerCurso.getColumnCount() - 1).setCellRenderer(new Render("Agregar", Color.GREEN));
        tblEscogerCurso.getColumnModel().getColumn(tblEscogerCurso.getColumnCount() - 1).setCellEditor(new ButtonEditor(Color.GREEN, "Agregar", new JCheckBox()));
    }//GEN-LAST:event_tblEscogerCursoMousePressed

    private void tblMatriculadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatriculadoMousePressed
        a = 1;
        int fila = tblMatriculado.getSelectedRow();
        if (fila != -1) {
            System.out.println("tablita: "+ (tblMatriculado.getRowCount() - 1));
            String Seccion = tblMatriculado.getValueAt(fila, tblMatriculado.getColumnModel().getColumnIndex("Seccion")).toString();
            M.setNroseccion(Integer.parseInt(Seccion));
            
            tblMatriculado.getColumnModel().getColumn(tblMatriculado.getColumnCount() - 1).setCellRenderer(new Render("Eliminar", Color.RED));
            tblMatriculado.getColumnModel().getColumn(tblMatriculado.getColumnCount() - 1).setCellEditor(new ButtonEditor(Color.RED, "Eliminar", new JCheckBox()));
        }


    }//GEN-LAST:event_tblMatriculadoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCarrera;
    private javax.swing.JLabel LblNombreCompleto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlCursosMatricular;
    private javax.swing.JTable tblEscogerCurso;
    private javax.swing.JTable tblMatriculado;
    // End of variables declaration//GEN-END:variables
}
