/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Frames_PanelsAlumno;

import DAO.HorarioCicloSeccion;
import Informacion.Alumno;
import Informacion.AlumnoDetallesCurso;
import Informacion.DocentexSecciones;
import Informacion.EstadoPeriodos;
import Informacion.NotasDetalles;
import Informacion.Usuario;
import Informacion.ValoresEstaticos;
import Interfaces.DAOAlumnoDetallesCursoImplement;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author medal
 */
public class PanelDetallesCurso extends javax.swing.JPanel {

    Usuario Usua = ValoresEstaticos.Usu;
    Alumno Alua = ValoresEstaticos.Alu;
    EstadoPeriodos VEPST = ValoresEstaticos.VEPST;
    AlumnoDetallesCurso ADC = new AlumnoDetallesCurso();
    DAOAlumnoDetallesCursoImplement DAOADC = new DAOAlumnoDetallesCursoImplement();
    int val = 0, contar = 0, Val2 = 0;
    HorarioCicloSeccion HS = new HorarioCicloSeccion();
    NotasDetalles ND = new NotasDetalles();
    NotasDetalles END = ValoresEstaticos.VEND;

    public PanelDetallesCurso() {
        initComponents();
        btnSimuPond.setEnabled(false);
        ADC.setAlumnoID(Usua.getID());
        DAOADC.CargarPeriodosxAlumno(ADC, CmbPeriodosxCursos);
        
//        LblNroCiclo.setText("" + Alua.getCiclo());
        if (CmbPeriodosxCursos.getItemCount() > 0) {
             
            DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) CmbPeriodosxCursos.getModel();

            for (int i = 0; i < model.getSize(); i++) {
                String elemento = model.getElementAt(i);
                if (elemento.equals(VEPST.getNombrep())) {
                    val++;
                }
            }
            if (val > 0) {
                CmbPeriodosxCursos.setSelectedItem(VEPST.getNombrep());
                ADC.setNomPeriodo(VEPST.getNombrep());
                DAOADC.CargarSeccionesxAlumno(ADC, tblDetallesCurso);
                String Cursonom = tblDetallesCurso.getValueAt(0, tblDetallesCurso.getColumnModel().getColumnIndex("Curso")).toString();
                int a = HS.CargarCiclo(Cursonom);
                LblNroCiclo.setText("" + a);
            } else {
                contar = CmbPeriodosxCursos.getItemCount();
                CmbPeriodosxCursos.setSelectedIndex((contar - 1));
                ADC.setNomPeriodo((String) CmbPeriodosxCursos.getItemAt((contar - 1)));
                DAOADC.CargarSeccionesxAlumno(ADC, tblDetallesCurso);
                String Cursonom = tblDetallesCurso.getValueAt(0, tblDetallesCurso.getColumnModel().getColumnIndex("Curso")).toString();
                int a = HS.CargarCiclo(Cursonom);
                LblNroCiclo.setText("" + a);
            }
              DAOADC.GuardarPromedios(ADC);
                if (Existe(ADC.getPonderado())) {
                LblPonderado.setText(Double.toString(ADC.getPonderado()));
            } else {
                LblPonderado.setText("-");
            }
            Val2 = 1;
        } else {
            jPanel3.setEnabled(false);
            jPanel3.setVisible(false);
            JOptionPane.showMessageDialog(null, "No tiene cursos actualmente en ningun periodo.");
            PanelLimpiarAlumno pLA = new PanelLimpiarAlumno();
            mostrarTipo(pLA);
        }
    }

    private String obtenerCursoDesdeCeldaSeleccionada() {
        // En un caso real, deberías implementar la lógica para obtener el curso desde la celda seleccionada
        // Aquí, simplemente devolvemos un valor de ejemplo
        return "Curso de Ejemplo";
    }

    public void mostrarTipo(JPanel j) {

        j.setSize(1160, 537);
        j.setLocation(0, 0);

        PnlDetallesCurso.removeAll();
        PnlDetallesCurso.add(j, BorderLayout.CENTER);
        PnlDetallesCurso.revalidate();
        PnlDetallesCurso.repaint();
    }

    public boolean Existe(double nota) {
        boolean existe;
        existe = (nota != 99);
//        System.out.println(nota);
        return existe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlDetallesCurso = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LblNroCiclo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetallesCurso = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        pnlVisualizadorNotas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LblNota1N = new javax.swing.JLabel();
        LblNota2N = new javax.swing.JLabel();
        LblNota3N = new javax.swing.JLabel();
        LblNota4N = new javax.swing.JLabel();
        LblNota1 = new javax.swing.JLabel();
        LblNota2 = new javax.swing.JLabel();
        LblNota4 = new javax.swing.JLabel();
        LblNota3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        LblPromCurso = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        LblPonderado = new javax.swing.JLabel();
        LblNota1Por = new javax.swing.JLabel();
        LblNota2Por = new javax.swing.JLabel();
        LblNota3Por = new javax.swing.JLabel();
        LblNota4Por = new javax.swing.JLabel();
        CmbPeriodosxCursos = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        btnSimuPond = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        PnlDetallesCurso.setBackground(new java.awt.Color(0, 102, 51));
        PnlDetallesCurso.setPreferredSize(new java.awt.Dimension(1160, 537));

        jPanel2.setBackground(new java.awt.Color(186, 46, 46));
        jPanel2.setPreferredSize(new java.awt.Dimension(1148, 63));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ver Cursos Matriculados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(362, 362, 362))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(237, 248, 248));

        LblNroCiclo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LblNroCiclo.setForeground(new java.awt.Color(0, 0, 0));
        LblNroCiclo.setText("-");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Horario:");

        lblHorario.setBackground(new java.awt.Color(255, 255, 255));
        lblHorario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblHorario.setForeground(new java.awt.Color(0, 0, 0));
        lblHorario.setText("-");
        lblHorario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Horario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        lblHorario.setPreferredSize(new java.awt.Dimension(150, 50));

        tblDetallesCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        tblDetallesCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Curso", "Seccion", "Docente"
            }
        ));
        tblDetallesCurso.setGridColor(new java.awt.Color(102, 102, 102));
        tblDetallesCurso.setRowHeight(30);
        tblDetallesCurso.setShowGrid(true);
        tblDetallesCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDetallesCursoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetallesCurso);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/wwww.png"))); // NOI18N

        pnlVisualizadorNotas.setBackground(new java.awt.Color(0, 153, 102));
        pnlVisualizadorNotas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 102, 51), null));
        pnlVisualizadorNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/clipp__1.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vista del avance en el Curso:");

        LblNota1N.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LblNota1N.setForeground(new java.awt.Color(255, 255, 255));
        LblNota1N.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblNota1N.setText("Nota1:");
        LblNota1N.setPreferredSize(new java.awt.Dimension(150, 30));

        LblNota2N.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LblNota2N.setForeground(new java.awt.Color(255, 255, 255));
        LblNota2N.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblNota2N.setText("Nota2:");
        LblNota2N.setPreferredSize(new java.awt.Dimension(150, 30));

        LblNota3N.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LblNota3N.setForeground(new java.awt.Color(255, 255, 255));
        LblNota3N.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblNota3N.setText("Nota3:");
        LblNota3N.setPreferredSize(new java.awt.Dimension(150, 30));

        LblNota4N.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        LblNota4N.setForeground(new java.awt.Color(255, 255, 255));
        LblNota4N.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblNota4N.setText("Nota4:");
        LblNota4N.setPreferredSize(new java.awt.Dimension(150, 30));

        LblNota1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNota1.setForeground(new java.awt.Color(255, 255, 255));
        LblNota1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNota1.setText("-");
        LblNota1.setPreferredSize(new java.awt.Dimension(40, 30));

        LblNota2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNota2.setForeground(new java.awt.Color(255, 255, 255));
        LblNota2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNota2.setText("-");
        LblNota2.setPreferredSize(new java.awt.Dimension(40, 30));

        LblNota4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNota4.setForeground(new java.awt.Color(255, 255, 255));
        LblNota4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNota4.setText("-");
        LblNota4.setPreferredSize(new java.awt.Dimension(40, 30));

        LblNota3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNota3.setForeground(new java.awt.Color(255, 255, 255));
        LblNota3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNota3.setText("-");
        LblNota3.setPreferredSize(new java.awt.Dimension(40, 30));

        jPanel4.setBackground(new java.awt.Color(153, 204, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 153, 0)));

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("Promedio:");

        LblPromCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LblPromCurso.setForeground(new java.awt.Color(255, 255, 255));
        LblPromCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPromCurso.setText("-");
        LblPromCurso.setPreferredSize(new java.awt.Dimension(50, 40));

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 102));
        jLabel24.setText("Promedio Ponderado:");

        LblPonderado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LblPonderado.setForeground(new java.awt.Color(255, 255, 255));
        LblPonderado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPonderado.setText("-");
        LblPonderado.setPreferredSize(new java.awt.Dimension(50, 40));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblPromCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(LblPonderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(LblPromCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(LblPonderado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        LblNota1Por.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNota1Por.setForeground(new java.awt.Color(255, 255, 255));
        LblNota1Por.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNota1Por.setText("%");
        LblNota1Por.setPreferredSize(new java.awt.Dimension(40, 30));

        LblNota2Por.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNota2Por.setForeground(new java.awt.Color(255, 255, 255));
        LblNota2Por.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNota2Por.setText("%");
        LblNota2Por.setPreferredSize(new java.awt.Dimension(40, 30));

        LblNota3Por.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNota3Por.setForeground(new java.awt.Color(255, 255, 255));
        LblNota3Por.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNota3Por.setText("%");
        LblNota3Por.setPreferredSize(new java.awt.Dimension(40, 30));

        LblNota4Por.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LblNota4Por.setForeground(new java.awt.Color(255, 255, 255));
        LblNota4Por.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNota4Por.setText("%");
        LblNota4Por.setPreferredSize(new java.awt.Dimension(40, 30));

        javax.swing.GroupLayout pnlVisualizadorNotasLayout = new javax.swing.GroupLayout(pnlVisualizadorNotas);
        pnlVisualizadorNotas.setLayout(pnlVisualizadorNotasLayout);
        pnlVisualizadorNotasLayout.setHorizontalGroup(
            pnlVisualizadorNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlVisualizadorNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGroup(pnlVisualizadorNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(LblNota1N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(LblNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(LblNota1Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addComponent(LblNota2N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(LblNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(LblNota2Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addComponent(LblNota3N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(LblNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(LblNota3Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addComponent(LblNota4N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(LblNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(LblNota4Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlVisualizadorNotasLayout.setVerticalGroup(
            pnlVisualizadorNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlVisualizadorNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(LblNota1N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(LblNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(LblNota1Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlVisualizadorNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNota2N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LblNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblNota2Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlVisualizadorNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNota3N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LblNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(LblNota3Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(pnlVisualizadorNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNota4N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(LblNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVisualizadorNotasLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(LblNota4Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CmbPeriodosxCursos.setBorder(javax.swing.BorderFactory.createTitledBorder("Periodo"));
        CmbPeriodosxCursos.setPreferredSize(new java.awt.Dimension(180, 50));
        CmbPeriodosxCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbPeriodosxCursosActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lapicito.png"))); // NOI18N

        btnSimuPond.setBackground(new java.awt.Color(102, 102, 0));
        btnSimuPond.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSimuPond.setText("Simular Ponderado");
        btnSimuPond.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimuPond.setPreferredSize(new java.awt.Dimension(180, 40));
        btnSimuPond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimuPondActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ciclo:");

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Periodo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addGap(16, 16, 16)
                .addComponent(CmbPeriodosxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LblNroCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel19)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVisualizadorNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnSimuPond, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(CmbPeriodosxCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNroCiclo)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel19)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))
                    .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pnlVisualizadorNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnSimuPond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout PnlDetallesCursoLayout = new javax.swing.GroupLayout(PnlDetallesCurso);
        PnlDetallesCurso.setLayout(PnlDetallesCursoLayout);
        PnlDetallesCursoLayout.setHorizontalGroup(
            PnlDetallesCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDetallesCursoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PnlDetallesCursoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnlDetallesCursoLayout.setVerticalGroup(
            PnlDetallesCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDetallesCursoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlDetallesCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlDetallesCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDetallesCursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetallesCursoMousePressed
        int fila = tblDetallesCurso.getSelectedRow();

        if (fila != -1) {
            String SeccionS = tblDetallesCurso.getValueAt(fila, tblDetallesCurso.getColumnModel().getColumnIndex("Seccion")).toString();
            int Seccion = Integer.parseInt(SeccionS);
            String H = HS.CargarHorario(Seccion, SeccionS);
            lblHorario.setText(H);
            ADC.setNroseccionAl(Integer.parseInt(SeccionS));
            DAOADC.CargarNotasxSeccion(ADC);
            LblNota1N.setText(ADC.getNotasNombres(0));
            LblNota2N.setText(ADC.getNotasNombres(1));
            LblNota3N.setText(ADC.getNotasNombres(2));
            LblNota4N.setText(ADC.getNotasNombres(3));
            LblNota1Por.setText("" + ADC.getNotasPorcentajes(0) + "%");
            LblNota2Por.setText("" + ADC.getNotasPorcentajes(1) + "%");
            LblNota3Por.setText("" + ADC.getNotasPorcentajes(2) + "%");
            LblNota4Por.setText("" + ADC.getNotasPorcentajes(3) + "%");
            if (Existe(ADC.getNotas(0))) {
                LblNota1.setText(Double.toString(ADC.getNotas(0)));
            } else {
                LblNota1.setText("-");
            }
            if (Existe(ADC.getNotas(1))) {
                LblNota2.setText(Double.toString(ADC.getNotas(1)));
            } else {
                LblNota2.setText("-");
            }
            if (Existe(ADC.getNotas(2))) {
                LblNota3.setText(Double.toString(ADC.getNotas(2)));
            } else {
                LblNota3.setText("-");
            }
            if (Existe(ADC.getNotas(3))) {
                LblNota4.setText(Double.toString(ADC.getNotas(3)));
            } else {
                LblNota4.setText("-");
            }
            if (Existe(ADC.getPF())) {
                LblPromCurso.setText(Double.toString(ADC.getPF()));
            } else {
                LblPromCurso.setText("-");
            }
          
        }
    }//GEN-LAST:event_tblDetallesCursoMousePressed

    private void btnSimuPondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimuPondActionPerformed
        PanelSimulador pSim = new PanelSimulador();
        mostrarTipo(pSim);
    }//GEN-LAST:event_btnSimuPondActionPerformed

    private void CmbPeriodosxCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbPeriodosxCursosActionPerformed
        if (Val2 == 1) {
            ADC.setNomPeriodo((String) CmbPeriodosxCursos.getSelectedItem());
            DAOADC.CargarSeccionesxAlumno(ADC, tblDetallesCurso);
            String Cursonom = tblDetallesCurso.getValueAt(0, tblDetallesCurso.getColumnModel().getColumnIndex("Curso")).toString();
            int a = HS.CargarCiclo(Cursonom);
                if (Existe(ADC.getPonderado())) {
                LblPonderado.setText(Double.toString(ADC.getPonderado()));
            } else {
                LblPonderado.setText("-");
            }
            LblNroCiclo.setText("" + a);
            Component[] components = pnlVisualizadorNotas.getComponents();
            for (Component component : components) {
                if (component instanceof JLabel) {
                    JLabel label = (JLabel) component;
                    if (!label.getText().equals("Vista del avance en el Curso:")) {
                        label.setText("-");
                    }
                }

            }
            LblPromCurso.setText("-");
         
            lblHorario.setText("-");
        }
        // System.out.println(alumno.getCarrera());
    }//GEN-LAST:event_CmbPeriodosxCursosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbPeriodosxCursos;
    private javax.swing.JLabel LblNota1;
    private javax.swing.JLabel LblNota1N;
    private javax.swing.JLabel LblNota1Por;
    private javax.swing.JLabel LblNota2;
    private javax.swing.JLabel LblNota2N;
    private javax.swing.JLabel LblNota2Por;
    private javax.swing.JLabel LblNota3;
    private javax.swing.JLabel LblNota3N;
    private javax.swing.JLabel LblNota3Por;
    private javax.swing.JLabel LblNota4;
    private javax.swing.JLabel LblNota4N;
    private javax.swing.JLabel LblNota4Por;
    private javax.swing.JLabel LblNroCiclo;
    private javax.swing.JLabel LblPonderado;
    private javax.swing.JLabel LblPromCurso;
    private javax.swing.JPanel PnlDetallesCurso;
    private javax.swing.JButton btnSimuPond;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JPanel pnlVisualizadorNotas;
    private javax.swing.JTable tblDetallesCurso;
    // End of variables declaration//GEN-END:variables
}
